### ISSUE TITLE
run visualize_result.py error( IndexError: invalid index to scalar variable)

### ISSUE THREAD

**Issue by gmt710** [JDAI-CV/fast-reid#105]
# enviroment
```
ubuntu16.04
cuda9.0
torch==1.1.0
torchvision==0.3.0
Cython
yacs
tensorboard
future
termcolor
sklearn
tqdm
opencv-python==4.1.0.25
matplotlib
```
I ran visualize_result.py and met this error.
```
python ./demo/visualize_result.py --config-file './configs/Market1501/AGW_R50.yml' --vis-label --dataset-name 'Market1501' --output 'logs/market1501/agw_R50/agw_market1501_vis' --opts MODEL.WEIGHTS "./logs/market1501/agw_R50/model_final.pth"
```

```
Traceback (most recent call last):
  File "./demo/visualize_result.py", line 139, in <module>
    args.rank_sort, args.label_sort, args.max_rank)
  File "./fastreid/utils/visualizer.py", line 157, in vis_rank_list
    self.save_rank_result(query_indices, output, max_rank, vis_label, label_sort, actmap)
  File "./fastreid/utils/visualizer.py", line 69, in save_rank_result
    ax.set_title('{}/{:.2f}/cam{}'.format(query_name, self.all_ap[q_idx], cam_id))
IndexError: invalid index to scalar variable.
```

Does anyone have this problem?

**Comment by L1aoXingyu** [comment]
maybe this is because your dataset not put in the right place, please check [here](https://github.com/JDAI-CV/fast-reid/blob/master/datasets/README.md).

**Comment by gmt710** [comment]
I check it.My dataset put in the right place.I can get the result but line 69 of visualizer.py.

**Comment by L1aoXingyu** [comment]
I think this problem caused by the evaluation function. You can update the evaluation cython code and recompile it.

**Comment by gmt710** [comment]
I solve this by modify:
修改/fast-reid-master/fastreid/evaluation/rank.py
```      
line182:      
use_cython=False```

**Comment by gmt710** [comment]
I'll close it.so feel free to reopen it

**Comment by gmt710** [comment]
I'll close it.so feel free to reopen it
