### ISSUE TITLE
AssertionError: Non-existent key: MODEL.DEVICE

### ISSUE THREAD

**Issue by soolone** [JDAI-CV/fast-reid#152]
When I use python ./tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml MODEL.DEVICE "cuda:0"
I got this error, how to fix it?

**Comment by L1aoXingyu** [comment]
Please use the latest updated code.

**Comment by YachaoDong** [comment]
> Please use the latest updated code.

Traceback (most recent call last):
  File "./tools/train_net.py", line 81, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 42, in main
    cfg = setup(args)
  File "./tools/train_net.py", line 34, in setup
    cfg.merge_from_file(args.config_file)
  File "./fastreid/config/config.py", line 110, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "./fastreid/config/config.py", line 121, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/root/anaconda3/envs/mm/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/root/anaconda3/envs/mm/lib/python3.7/site-packages/yacs/config.py", line 464, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/root/anaconda3/envs/mm/lib/python3.7/site-packages/yacs/config.py", line 477, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: SOLVER.LOG_PERIOD'

你好，我也遇到了类似的错误，请问是哪里出了问题了吗？使用的是最新的代码

**Comment by L1aoXingyu** [comment]
which config file do you use？

**Comment by liuzhonghuacd** [comment]
Traceback (most recent call last):
  File "e:\fast-reid\tools\train_net.py", line 81, in <module>
    args=(args,),
  File ".\fastreid\engine\launch.py", line 71, in launch
    main_func(*args)
  File "e:\fast-reid\tools\train_net.py", line 42, in main
    cfg = setup(args)
  File "e:\fast-reid\tools\train_net.py", line 34, in setup
    cfg.merge_from_file(args.config_file)
  File ".\fastreid\config\config.py", line 110, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File ".\fastreid\config\config.py", line 121, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "C:\Anaconda3\lib\site-packages\yacs-0.1.6-py3.6.egg\yacs\config.py", line 217, in merge_from_other_cfg
  File "C:\Anaconda3\lib\site-packages\yacs-0.1.6-py3.6.egg\yacs\config.py", line 464, in _merge_a_into_b
  File "C:\Anaconda3\lib\site-packages\yacs-0.1.6-py3.6.egg\yacs\config.py", line 477, in _merge_a_into_b
KeyError: 'Non-existent config key: SOLVER.LOG_PERIOD'
hi, I used the latest code, the same problem existed. how to fix it? Thanks!

**Comment by YachaoDong** [comment]
> which config file do you use？ @YachaoDong

VeRi  sbs_R50-ibn.yml

**Comment by L1aoXingyu** [comment]
@YachaoDong @liuzhonghuacd 
I have updated config files, pls try it again.

**Comment by YachaoDong** [comment]
> @YachaoDong @liuzhonghuacd
> I have updated config files, pls try it again.

感谢，问题已被解决！
