### ISSUE TITLE
how to find the package rfconv

### ISSUE THREAD

**Issue by xiaopanchen** [JDAI-CV/fast-reid#165]
can you tell me how to find the rfconv.

**Comment by xiaopanchen** [comment]
In order to use rfconv, I have copy the folder "functions、lib、nn" from Zhanghang's project "Pytorch_encoding" to this project, but there are errors below.
出现了下面的错误
C:\ProgramData\Anaconda3\python.exe D:/fast-reid-20200711/tools/train_net.py --config-file ../configs/Market1501/bagtricks_R50.yml MODEL.DEVICE cuda:0
C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:209: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1066, in _build_extension_module
check=True)
File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 512, in run
output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:/fast-reid-20200711/tools/train_net.py", line 15, in
from fastreid.engine import DefaultTrainer, default_argument_parser, default_setup, launch
File "D:\fast-reid-20200711\fastreid\engine_init_.py", line 14, in
from .defaults import *
File "D:\fast-reid-20200711\fastreid\engine\defaults.py", line 24, in
from fastreid.modeling.meta_arch import build_model
File "D:\fast-reid-20200711\fastreid\modeling_init_.py", line 7, in
from .meta_arch import build_model
File "D:\fast-reid-20200711\fastreid\modeling\meta_arch_init_.py", line 11, in
from .baseline import Baseline
File "D:\fast-reid-20200711\fastreid\modeling\meta_arch\baseline.py", line 11, in
from fastreid.modeling.backbones import build_backbone
File "D:\fast-reid-20200711\fastreid\modeling\backbones_init_.py", line 11, in
from .resnest import build_resnest_backbone
File "D:\fast-reid-20200711\fastreid\modeling\backbones\resnest.py", line 9, in
from ..nn.rectify import RFConv2d
File "D:\fast-reid-20200711\fastreid\modeling\nn_init_.py", line 12, in
from .encoding import *
File "D:\fast-reid-20200711\fastreid\modeling\nn\encoding.py", line 18, in
from ..functions import scaled_l2, aggregate, pairwise_cosine
File "D:\fast-reid-20200711\fastreid\modeling\functions_init_.py", line 2, in
from .encoding import *
File "D:\fast-reid-20200711\fastreid\modeling\functions\encoding.py", line 14, in
from .. import lib
File "D:\fast-reid-20200711\fastreid\modeling\lib_init_.py", line 16, in
], build_directory=cpu_path, verbose=False)
File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 680, in load
is_python_module)
File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 866, in _jit_compile
with_cuda=with_cuda)
File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 919, in _write_ninja_file_and_build
_build_extension_module(name, build_directory, verbose)
File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1078, in _build_extension_module
message += ": {}".format(error.output.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 1038: invalid continuation byte

Process finished with exit code 1

**Comment by L1aoXingyu** [comment]
You can ask zhanghang where is rfconv, and actually I don't use this layer.

**Comment by xiaopanchen** [comment]
> You can ask zhanghang where is rfconv, and actually I don't use this layer.

thank you
