### ISSUE TITLE
partial-reid got wrong during evaluate

### ISSUE THREAD

**Issue by Akaneqwq** [JDAI-CV/fast-reid#169]
When I want to train partial-reid project, everything goes right when training, but when the code try to eval the results, project gets an error, here is my error information:
```
[07/13 22:31:09 fastreid.data.datasets.bases]: => Loaded PartialiLIDS
[07/13 22:31:09 fastreid.data.datasets.bases]:   ----------------------------------------
[07/13 22:31:09 fastreid.data.datasets.bases]:   subset   | # ids | # images | # cameras
[07/13 22:31:09 fastreid.data.datasets.bases]:   ----------------------------------------
[07/13 22:31:09 fastreid.data.datasets.bases]:   query    |   119 |      119 |         1
[07/13 22:31:09 fastreid.data.datasets.bases]:   gallery  |   119 |      119 |         1
[07/13 22:31:09 fastreid.data.datasets.bases]:   ----------------------------------------
[07/13 22:31:09 fastreid.evaluation.evaluator]: Start inference on 238 images
ERROR [07/13 22:31:13 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/brl/fast-reid/fastreid/engine/train_loop.py", line 125, in train
    self.after_step()
  File "/home/brl/fast-reid/fastreid/engine/train_loop.py", line 145, in after_step
    h.after_step()
  File "/home/brl/fast-reid/fastreid/engine/hooks.py", line 338, in after_step
    self._do_eval()
  File "/home/brl/fast-reid/fastreid/engine/hooks.py", line 313, in _do_eval
    results = self._func()
  File "/home/brl/fast-reid/fastreid/engine/defaults.py", line 315, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/home/brl/fast-reid/fastreid/engine/defaults.py", line 465, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/brl/fast-reid/fastreid/evaluation/evaluator.py", line 118, in inference_on_dataset
    evaluator.process(inputs, outputs)
TypeError: process() takes 2 positional arguments but 3 were given
[07/13 22:31:13 fastreid.engine.hooks]: Overall training speed: 1197 iterations in 0:06:53 (0.3453 s / it)
[07/13 22:31:13 fastreid.engine.hooks]: Total training time: 0:06:57 (0:00:04 on hooks)
Traceback (most recent call last):
  File "projects/PartialReID/train_net.py", line 83, in <module>
    args=(args,),
  File "/home/brl/fast-reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "projects/PartialReID/train_net.py", line 71, in main
    return trainer.train()
  File "/home/brl/fast-reid/fastreid/engine/defaults.py", line 365, in train
    ), "No evaluation results obtained during training!"
AssertionError: No evaluation results obtained during training!

```
How can I fix the error and evaluate the results?

**Comment by Deepcong2019** [comment]
Have you solved it ？

**Comment by L1aoXingyu** [comment]
Please use the latest code.

**Comment by GesilaA** [comment]
@L1aoXingyu the same question I had. In Market1501set, when I set the camera id to 'c1s1', the same problem occurred. Is camera_num > 1?

**Comment by L1aoXingyu** [comment]
fixed.
