### ISSUE TITLE
Invalid type <class 'fastreid.config.config.CfgNode'> for key MODEL

### ISSUE THREAD

**Issue by zt1112** [JDAI-CV/fast-reid#176]
有人遇到这个问题吗
cmd:
python ./tools/train_net.py --config-file ./configs/DukeMTMC/bagtricks_R50-ibn.yml

结果：
Traceback (most recent call last):
  File "./tools/train_net.py", line 14, in <module>
    from fastreid.config import get_cfg
  File "./fastreid/config/__init__.py", line 8, in <module>
    from .defaults import _C as cfg
  File "./fastreid/config/defaults.py", line 22, in <module>
    _C.MODEL = CN()
  File "./fastreid/config/config.py", line 150, in __setattr__
    super().__setattr__(name, val)
  File "/data/home/vinniezhang/anaconda3/lib/python3.6/site-packages/yacs/config.py", line 100, in __setattr__
    type(value), name, _VALID_TYPES
AssertionError: Invalid type <class 'fastreid.config.config.CfgNode'> for key MODEL; valid types = {<class 'dict'>, <class 'tuple'>, <class 'list'>, <class 'bool'>, <class 'int'>, <class 'str'>, <class 'float'>}

**Comment by zt1112** [comment]
solved

**Comment by lvyan2001** [comment]
how to solve this problem? i've meet the same problem, thank you

**Comment by twj1999** [comment]
你好，请问你怎么解决这个问题，我也遇到了，谢谢

**Comment by twj1999** [comment]
> solved

hello,how to solve this.i met this too.thank u!

**Comment by twj1999** [comment]
> how to solve this problem? i've meet the same problem, thank you

have you solved this problem? i met too. Need he了p, thanks！
