### ISSUE TITLE
IndexError: pop from empty list when training market1501 and my own cuhk01 dataset together.

### ISSUE THREAD

**Issue by ChongZhangZC** [JDAI-CV/fast-reid#180]
**IndexError: pop from empty list** when training market1501 and cuhk01 together.  The cuhk01.py is edited according to cuhk03.py.
**There is no error when training them separately.**
Do I need to make more changes for joint training? Thank you!

## Unexpeted behaviors:
Traceback (most recent call last):
  File "./tools/train_net.py", line 81, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 67, in main
    trainer = Trainer(cfg)
  File "./fastreid/engine/defaults.py", line 217, in __init__
    super().__init__(model, data_loader, optimizer)
  File "./fastreid/engine/train_loop.py", line 186, in __init__
    self._data_loader_iter = iter(data_loader)
  File "/home/user/anaconda3/envs/pytorch-cvpr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/user/anaconda3/envs/pytorch-cvpr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 709, in __init__
    self._try_put_index()
  File "/home/user/anaconda3/envs/pytorch-cvpr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 826, in _try_put_index
    index = self._next_index()
  File "/home/user/anaconda3/envs/pytorch-cvpr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 318, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/user/anaconda3/envs/pytorch-cvpr/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "./fastreid/data/samplers/triplet_sampler.py", line 169, in __iter__
    yield from itertools.islice(self._infinite_indices(), start, None, self._world_size)
  File "./fastreid/data/samplers/triplet_sampler.py", line 174, in _infinite_indices
    indices = self._get_epoch_indices()
  File "./fastreid/data/samplers/triplet_sampler.py", line 161, in _get_epoch_indices
    batch_idxs = batch_idxs_dict[pid].pop(0)
IndexError: pop from empty list

## Instructions To Reproduce the Issue:
```
1. cuhk.py
from __future__ import division, print_function, absolute_import
import json
import glob
import numpy as np
import os.path as osp
import zipfile

from fastreid.data.datasets import DATASET_REGISTRY
from .bases import ImageDataset
from fastreid.utils.file_io import PathManager


@DATASET_REGISTRY.register()
class CUHK01(ImageDataset):

    dataset_dir = 'cuhk01'
    dataset_url = None

    def __init__(self, root='', split_id=0, **kwargs):
        self.root = osp.abspath(osp.expanduser(root))
        self.dataset_dir = osp.join(self.root, self.dataset_dir)
        #self.download_dataset(self.dataset_dir, self.dataset_url)

        self.zip_path = osp.join(self.dataset_dir, 'CUHK01.zip')
        self.campus_dir = osp.join(self.dataset_dir, 'campus')
        self.split_path = osp.join(self.dataset_dir, 'splits.json')

        self.extract_file()

        required_files = [self.dataset_dir, self.campus_dir]
        self.check_before_run(required_files)

        self.prepare_split()
        with PathManager.open(self.split_path) as f:
        	splits = json.load(f)
        assert split_id < len(splits), 'split_id exceeds range, received {}, but expected between 0 and {}'
        								.format(split_id,len(splits) - 1)
        split = splits[split_id]

        train = split['train']
        query = split['query']
        gallery = split['gallery']

        train = [tuple(item) for item in train]
        query = [tuple(item) for item in query]
        gallery = [tuple(item) for item in gallery]

        super(CUHK01, self).__init__(train, query, gallery, **kwargs)

    def extract_file(self):
        if not osp.exists(self.campus_dir):
            print('Extracting files')
            zip_ref = zipfile.ZipFile(self.zip_path, 'r')
            zip_ref.extractall(self.dataset_dir)
            zip_ref.close()

    def prepare_split(self):
        """
        Image name format: 0001001.png, where first four digits represent identity
        and last four digits represent cameras. Camera 1&2 are considered the same
        view and camera 3&4 are considered the same view.
        """
        if not osp.exists(self.split_path):
            print('Creating 10 random splits of train ids and test ids')
            img_paths = sorted(glob.glob(osp.join(self.campus_dir, '*.png')))
            img_list = []
            pid_container = set()
            for img_path in img_paths:
                img_name = osp.basename(img_path)
                pid = int(img_name[:4]) - 1
                camid = (int(img_name[4:7]) - 1) // 2 # result is either 0 or 1
                img_list.append((img_path, pid, camid))
                pid_container.add(pid)

            num_pids = len(pid_container)
            num_train_pids = num_pids // 2

            splits = []
            for _ in range(10):
                order = np.arange(num_pids)
                np.random.shuffle(order)
                train_idxs = order[:num_train_pids]
                train_idxs = np.sort(train_idxs)
                idx2label = {
                    idx: label
                    for label, idx in enumerate(train_idxs)
                }

                train, test_a, test_b = [], [], []
                for img_path, pid, camid in img_list:
                    if pid in train_idxs:
                        train.append((img_path, idx2label[pid], camid))
                    else:
                        if camid == 0:
                            test_a.append((img_path, pid, camid))
                        else:
                            test_b.append((img_path, pid, camid))

                # use cameraA as query and cameraB as gallery
                split = {
                    'train': train,
                    'query': test_a,
                    'gallery': test_b,
                    'num_train_pids': num_train_pids,
                    'num_query_pids': num_pids - num_train_pids,
                    'num_gallery_pids': num_pids - num_train_pids
                }
                splits.append(split)

                # use cameraB as query and cameraA as gallery
                split = {
                    'train': train,
                    'query': test_b,
                    'gallery': test_a,
                    'num_train_pids': num_train_pids,
                    'num_query_pids': num_pids - num_train_pids,
                    'num_gallery_pids': num_pids - num_train_pids
                }
                splits.append(split)

            print('Totally {} splits are created'.format(len(splits)))
            with PathManager.open(self.split_path,'w') as f:
            	json.dump(splits, f, indent=4, separators=(',', ': '))
            print('Split file saved to {}'.format(self.split_path))
```

**Comment by ChongZhangZC** [comment]
pid is formated as self.dataset_name+"_"+str(pid) for joint training.
I forgot to do it when prepare splits.
