### ISSUE TITLE
about pretrain model path

### ISSUE THREAD

**Issue by zengwbz** [JDAI-CV/fast-reid#208]
最新版本找不到ibn预训练模型路径设置的地方了，很不方便。

**Comment by L1aoXingyu** [comment]
现在不用自己设置 pre-train model path，是为了对新手同学更友好一点 😂

**Comment by Angel0003** [comment]
> 现在不用自己设置 pre-train model path，会自己找到默认路径，是为了对新手同学更友好一点 joy

给出的链接下载的预训练模型resnet50_ibn_a.pth.tar怎么不能解压，解压的时候提示已经被破坏https://drive.google.com/drive/folders/1thS2B8UOSBi_cJX6zRy6YYRwz_nVFI_S，请问怎么解决？

**Comment by Angel0003** [comment]
给出的链接下载的预训练模型resnet50_ibn_a.pth.tar怎么不能解压，解压的时候提示已经被破坏https://drive.google.com/drive/folders/1thS2B8UOSBi_cJX6zRy6YYRwz_nVFI_S，请问怎么解决？

**Comment by Angel0003** [comment]
(tensorflow) lla@lla:~/.cache/torch/checkpoints$ ls
r50_ibn_a.pth  resnet101_ibn_b.pth
我已经在我的torch下放好了预训练模型，上面是我放预训练模型的地址。为什么运行还是会重新下载一个resnet50_ibn_a-d9d0bb7b.pth模型,而且还报下面的错误，请问怎么解决？


[08/07 08:47:19 fastreid]: Full config saved to /home/ycl/Downloads/MQQ/fast-reid/logs/veri/sbs_R50-ibn/config.yaml
[08/07 08:47:19 fastreid.utils.env]: Using a generated random seed 19468109
[08/07 08:47:19 fastreid.engine.defaults]: Prepare training set
[08/07 08:47:19 fastreid.data.datasets.bases]: => Loaded VeRi in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| train    | 576     | 37778      | 20          |
[08/07 08:47:19 fastreid.engine.defaults]: Auto-scaling the config to num_classes=576, max_Iter=70800, wamrup_Iter=11800, freeze_Iter=11800, delay_Iter=35400, step_Iter=[47200, 106200], ckpt_Iter=23600, eval_Iter=23600.
Downloading...
From: https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet50_ibn_a-d9d0bb7b.pth
To: /home/lla/.cache/torch/checkpoints/resnet50_ibn_a-d9d0bb7b.pth
  1%|▊                                                                                   | 1.05M/102M [00:15<24:43, 68.4kB/s]^CTraceback (most recent call last):
  File "./tools/train_net.py", line 67, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 53, in main
    trainer = Trainer(cfg)
  File "./fastreid/engine/defaults.py", line 206, in __init__
    model = self.build_model(cfg)
  File "./fastreid/engine/defaults.py", line 374, in build_model
    model = build_model(cfg)
  File "./fastreid/modeling/meta_arch/build.py", line 24, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "./fastreid/modeling/meta_arch/baseline.py", line 27, in __init__
    self.backbone = build_backbone(cfg)
  File "./fastreid/modeling/backbones/build.py", line 27, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg)
  File "./fastreid/modeling/backbones/resnet.py", line 336, in build_resnet_backbone
    state_dict = init_pretrained_weights(key)
  File "./fastreid/modeling/backbones/resnet.py", line 277, in init_pretrained_weights
    gdown.download(model_urls[key], cached_file, quiet=False)
  File "/home/lla/anaconda3/envs/tensorflow/lib/python3.6/site-packages/gdown/download.py", line 197, in download
    for chunk in res.iter_content(chunk_size=CHUNK_SIZE):
  File "/home/lla/.local/lib/python3.6/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/lla/.local/lib/python3.6/site-packages/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/lla/.local/lib/python3.6/site-packages/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/lla/anaconda3/envs/tensorflow/lib/python3.6/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/home/lla/anaconda3/envs/tensorflow/lib/python3.6/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/home/lla/anaconda3/envs/tensorflow/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/lla/.local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/home/lla/anaconda3/envs/tensorflow/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1839, in recv_into
    result = _lib.SSL_read(self._ssl, buf, nbytes)
KeyboardInterrupt
  1%|▊                                                                                   | 1.05M/102M [00:17<27:31, 61.4kB/s]

**Comment by Angel0003** [comment]
> 现在不用自己设置 pre-train model path，会自己找到默认路径，是为了对新手同学更友好一点 joy


# If use ImageNet pretrain model
_C.MODEL.BACKBONE.PRETRAIN = True
# Pretrain model path
_C.MODEL.BACKBONE.PRETRAIN_PATH = '/home/lla/.cache/torch/checkpoints/resnet101_ibn_b.pth'
你好，我在这里设置了预训练模型的地址，然后运行 python ./tools/train_net.py --config-file ./configs/VeRi/sbs_R50-ibn.yml 
报如下错误，请问怎么解决？
[08/07 10:36:04 fastreid.modeling.backbones.resnet]: State dict keys error! Please check the state dict.
Traceback (most recent call last):
  File "./tools/train_net.py", line 67, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 53, in main
    trainer = Trainer(cfg)
  File "./fastreid/engine/defaults.py", line 206, in __init__
    model = self.build_model(cfg)
  File "./fastreid/engine/defaults.py", line 374, in build_model
    model = build_model(cfg)
  File "./fastreid/modeling/meta_arch/build.py", line 24, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "./fastreid/modeling/meta_arch/baseline.py", line 27, in __init__
    self.backbone = build_backbone(cfg)
  File "./fastreid/modeling/backbones/build.py", line 27, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg)
  File "./fastreid/modeling/backbones/resnet.py", line 330, in build_resnet_backbone
    raise e
  File "./fastreid/modeling/backbones/resnet.py", line 316, in build_resnet_backbone
    state_dict = torch.load(pretrain_path, map_location=torch.device('cpu'))['model']
KeyError: 'model'
下载的预训练模型名字和
logger = logging.getLogger(__name__)
model_urls = {
    '18x': 'https://download.pytorch.org/models/resnet18-5c106cde.pth',
    '34x': 'https://download.pytorch.org/models/resnet34-333f7ec4.pth',
    '50x': 'https://download.pytorch.org/models/resnet50-19c8e357.pth',
    '101x': 'https://download.pytorch.org/models/resnet101-5d3b4d8f.pth',
    'ibn_18x': 'https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet18_ibn_a-2f571257.pth',
    'ibn_34x': 'https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet34_ibn_a-94bc1577.pth',
    'ibn_50x': 'https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet50_ibn_a-d9d0bb7b.pth',
    'ibn_101x': 'https://github.com/XingangPan/IBN-Net/releases/download/v1.0/resnet101_ibn_a-59ea0ac6.pth',
    'se_ibn_101x': 'https://github.com/XingangPan/IBN-Net/releases/download/v1.0/se_resnet101_ibn_a-fabed4e2.pth',
}这里模型名字为什么不一样？

**Comment by L1aoXingyu** [comment]
现在又可以自己设置 `pretrain_path` 了
