### ISSUE TITLE
How to train model in multi-gpu in a single machine?

### ISSUE THREAD

**Issue by hbchen121** [JDAI-CV/fast-reid#212]
## ❓ How to train model in multi-gpu in a single machine?

while I run ./tools/train_net.py with command-line:
`CUDA_VISIBLE_DEVICES=1 python ./tools/train_net.py --config-file /home/hbchen/fastreid_baseline/fast-reid-0.1-Learning/configs/VehicleID/bagtricks_R50-ibn.yml --machine-rank 1 --num-gpus 1`
**it works well**.

But when I use 
`CUDA_VISIBLE_DEVICES=2,3 python ./tools/train_net.py --config-file /home/hbchen/fastreid_baseline/fast-reid-0.1-Learning/configs/VehicleID/bagtricks_R50-ibn.yml --machine-rank 1 --num-gpus 2`
to train model in **multi-gpu**, there's something wrong with the program. And I type Ctrl+C twice to interrupt it. 
Specific as follows：

```
CUDA_VISIBLE_DEVICES=2,3 python ./tools/train_net.py --config-file /home/hbchen/fastreid_baseline/fast-reid-0.1-Learning/configs/VehicleID/bagtricks_R50-ibn.yml --machine-rank 1 --num-gpus 2 --dist-url auto
Command Line Args: Namespace(config_file='/home/hbchen/fastreid_baseline/fast-reid-0.1-Learning/configs/VehicleID/bagtricks_R50-ibn.yml', dist_url='auto', eval_only=False, machine_rank=1, num_gpus=2, num_machines=1, opts=[], resume=False)
^CTraceback (most recent call last):
  File "./tools/train_net.py", line 67, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 68, in launch
    daemon=False,
  File "/home/hbchen/anaconda3/envs/fastreid/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/home/hbchen/anaconda3/envs/fastreid/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 73, in join
    timeout=timeout,
  File "/home/hbchen/anaconda3/envs/fastreid/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/home/hbchen/anaconda3/envs/fastreid/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/hbchen/anaconda3/envs/fastreid/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
**Looking forward to your reply. Thanks!**

**Comment by hbchen121** [comment]
I had got it. Machine rank should be 0 when use a single machine. I'm such a fool.
