### ISSUE TITLE
Unexpected error when training

### ISSUE THREAD

**Issue by Angel0003** [JDAI-CV/fast-reid#223]
[08/07 20:10:46 fastreid.utils.events]: eta: 5:39:19  iter: 14199  total_loss: 37.211  loss_cls: 35.876  loss_triplet: 1.078  time: 0.3492  data_time: 0.0010  lr: 1.00e-02  max_mem: 5691M
[08/07 20:11:58 fastreid.utils.events]: eta: 5:38:05  iter: 14399  total_loss: 30.389  loss_cls: 29.702  loss_triplet: 0.518  time: 0.3494  data_time: 0.0010  lr: 1.00e-02  max_mem: 5691M
[08/07 20:13:10 fastreid.utils.events]: eta: 5:36:53  iter: 14599  total_loss: 27.272  loss_cls: 26.761  loss_triplet: 0.352  time: 0.3495  data_time: 0.0010  lr: 1.00e-02  max_mem: 5691M
ERROR [08/07 20:13:36 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "./fastreid/engine/train_loop.py", line 124, in train
    self.run_step()
  File "./fastreid/engine/train_loop.py", line 213, in run_step
    self._detect_anomaly(losses, loss_dict)
  File "./fastreid/engine/train_loop.py", line 236, in _detect_anomaly
    self.iter, loss_dict
FloatingPointError: Loss became infinite or NaN at iteration=14671!
loss_dict = {'loss_cls': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>), 'loss_triplet': tensor(nan, device='cuda:0', grad_fn=<MulBackward0>)}
[08/07 20:13:36 fastreid.engine.hooks]: Overall training speed: 14669 iterations in 1:25:28 (0.3496 s / it)
[08/07 20:13:36 fastreid.engine.hooks]: Total training time: 1:25:31 (0:00:02 on hooks)
Traceback (most recent call last):
  File "./tools/train_net.py", line 67, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 55, in main
    return trainer.train()
  File "./fastreid/engine/defaults.py", line 362, in train
    ), "No evaluation results obtained during training!"
AssertionError: No evaluation results obtained during training!
      
     I encountered the following error during training，could you tell me,how to solve the problem?thanks a lot!

**Comment by duyuanchao** [comment]
seems something wrong with your loss, can you provide the complete config, and the latest 10 epoch loss value?

> self.iter, loss_dict
> FloatingPointError: Loss became infinite or NaN at iteration=14671!
> loss_dict = {'loss_cls': tensor(nan, device='cuda:0', grad_fn=), 'loss_triplet': tensor(nan, device='cuda:0', grad_fn=)}
