### ISSUE TITLE
caffe_export: KeyError

### ISSUE THREAD

**Issue by SuQinghang** [JDAI-CV/fast-reid#261]
你好，在使用`caffe_export.py`导出模型的caffe形式时遇到下列问题
......
e.layer4.2.se', BNneckHead(
  (pool_layer): Identity()
  (hash): Linear(in_features=2048, out_features=128, bias=True)
  (bnneck): BatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (classifier): CircleSoftmax(in_features=128, num_classes=575, scale=64, margin=0.35)
): 'heads', Identity(): 'heads.pool_layer', Linear(in_features=2048, out_features=128, bias=True): 'heads.hash', BatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True): 'heads.bnneck', CircleSoftmax(in_features=128, num_classes=575, scale=64, margin=0.35): 'heads.classifier'}
sub1 was added to layers
140554275026816:sub_blob1 was added to blobs
Add blob       sub_blob1       : torch.Size([1, 3, 128, 64])
140554280463328:blob1 getting
Traceback (most recent call last):
  File "caffe_export.py", line 75, in <module>
    pytorch_to_caffe.trans_net(model, inputs, args.name)
  File "/data2/suqinghang/ReID/fast-reid-new/tools/deploy/pytorch_to_caffe.py", line 738, in trans_net
    out = net.forward(input_var)
  File "../../fastreid/modeling/meta_arch/baseline.py", line 36, in forward
    images = self.preprocess_image(batched_inputs)
  File "../../fastreid/modeling/meta_arch/baseline.py", line 70, in preprocess_image
    images = (images - self.pixel_mean) / self.pixel_std
  File "/data2/suqinghang/ReID/fast-reid-new/tools/deploy/pytorch_to_caffe.py", line 587, in _sub
    bottom=[log.blobs(input), log.blobs(args[0])], top=top_blobs)
  File "/data2/suqinghang/ReID/fast-reid-new/tools/deploy/pytorch_to_caffe.py", line 101, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "/data2/suqinghang/ReID/fast-reid-new/tools/deploy/pytorch_to_caffe.py", line 39, in __getitem__
    return self.data[key]
KeyError: 140554275221744

在尝试 #232 中提出的解决方法之后没有效果，请问这个bug应该怎么解决？
我使用的backbone是resnet50-ibn-a

**Comment by L1aoXingyu** [comment]
ibn-net 不支持 caffe export

**Comment by pudongdong** [comment]
> 
> 
> ibn-net 不支持 caffe export

resnet50也是同样问题呢
