### ISSUE TITLE
Triplet loss error when multi-gpu training

### ISSUE THREAD

**Issue by claylau** [JDAI-CV/fast-reid#282]
triplet loss doesn't work when using multi-gpu train.

> [09/24 11:11:02 fastreid.engine.defaults]: Freeze layer group "backbone" training for 10730 iterations
[09/24 11:11:02 fastreid.utils.checkpoint]: No checkpoint found. Training model from scratch
[09/24 11:11:02 fastreid.engine.train_loop]: Starting training from iteration 0
ERROR [09/24 11:11:05 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/xd133/fast-reid/fastreid/engine/train_loop.py", line 125, in train
    self.run_step()
  File "/home/xd133/fast-reid/fastreid/engine/train_loop.py", line 216, in run_step
    loss_dict = self.model.module.losses(outs)
  File "/home/xd133/fast-reid/fastreid/modeling/meta_arch/baseline.py", line 105, in losses
    self._cfg.MODEL.LOSSES.TRI.HARD_MINING,
  File "/home/xd133/fast-reid/fastreid/modeling/losses/triplet_loss.py", line 106, in triplet_loss
    dist_ap, dist_an = hard_example_mining(dist_mat, is_pos, is_neg)
  File "/home/xd133/fast-reid/fastreid/modeling/losses/triplet_loss.py", line 45, in hard_example_mining
    dist_mat[is_pos].contiguous().view(N, -1), 1, keepdim=True)
RuntimeError: shape '[64, -1]' is invalid for input of size 352
[09/24 11:11:05 fastreid.engine.hooks]: Overall training speed: 2 iterations in 0:00:00 (0.1370 s / it)
[09/24 11:11:05 fastreid.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)

dist_mat[is_pos] has size 352 but N equal 64.

I use 4 gpus with batch size 64.

**Comment by claylau** [comment]
the bug seems to be there: `fast-reid/fastreid/modeling/losses/triplet_loss.py`

```
dist_mat = euclidean_dist(all_embedding, all_embedding)

N = dist_mat.size(0)
is_pos = all_targets.view(N, 1).expand(N, N).eq(all_targets.view(N, 1).expand(N, N).t())
is_neg = all_targets.view(N, 1).expand(N, N).ne(all_targets.view(N, 1).expand(N, N).t())
```

change to following
```
dist_mat = euclidean_dist(embedding, all_embedding)

N, M = dist_mat.size()
is_pos = targets.view(N, 1).expand(N, M).eq(all_targets.view(M, 1).expand(M, N).t())
is_neg = targets.view(N, 1).expand(N, M).ne(all_targets.view(M, 1).expand(M, N).t())       
```

**Comment by L1aoXingyu** [comment]
Please use the latest code and provide information as the issue template.
