### ISSUE TITLE
DistillReid KeyError: 'Non-existent config key: MODEL.HEADS.IN_FEAT'

### ISSUE THREAD

**Issue by gouravvemula** [JDAI-CV/fast-reid#287]
while using distill reid I am getting KeyError: 'Non-existent config key: MODEL.HEADS.IN_FEAT' using KD-bot50ibn-bot18.yml for both dukemtcm and market1501 config files. I used pretrained model from model zoo

Traceback (most recent call last):
  File "./projects/DistillReID/train_net.py", line 62, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./projects/DistillReID/train_net.py", line 35, in main
    cfg = setup(args)
  File "./projects/DistillReID/train_net.py", line 27, in setup
    cfg.merge_from_file(args.config_file)
  File "./fastreid/config/config.py", line 112, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "./fastreid/config/config.py", line 124, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: MODEL.HEADS.IN_FEAT'

I have also tried with other config file provided in DistillReid and got same error

**Comment by L1aoXingyu** [comment]
This is due to the fastreid version change. I will fix it later.

**Comment by L1aoXingyu** [comment]
fixed.
