### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'm'. -- During evaluation, failed to load trained model.

### ISSUE THREAD

**Issue by linjiawen2019** [JDAI-CV/fast-reid#301]
@L1aoXingyu  Hi, I met a pickle problem when I evaluated the model performance after I finished training. It couldn't load the model. Here's the command:
“python tools/train_net.py --config-file ./configs/Market1501/sbs_R50-ibn.yml --eval-only MODEL.WEIGHTS /disk1/home/yiming-zhu/fast-reid/logs/market1501/sbs_R50-ibn/last-checkpoint MODEL.DEVICE "cuda:0"
”
And the Error:
"
Traceback (most recent call last):
  File "tools/train_net.py", line 81, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "tools/train_net.py", line 50, in main
    Checkpointer(model).load(cfg.MODEL.WEIGHTS)  # load trained model
  File "./fastreid/utils/checkpoint.py", line 101, in load
    checkpoint = self._load_file(path)
  File "./fastreid/utils/checkpoint.py", line 184, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/opt/anaconda/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/opt/anaconda/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'm'.
"

Do you know how to deal with this?

**Comment by L1aoXingyu** [comment]
`last-checkpoint` is not the saved model. `*.pth` is the saved model.

**Comment by linjiawen2019** [comment]
> `last-checkpoint` is not the saved model. `*.pth` is the saved model.

Thank you so much!! I thought it should be the "last_checkpoint" path....
