### ISSUE TITLE
AssertionError: No evaluation results obtained during training!

### ISSUE THREAD

**Issue by zengwbz** [JDAI-CV/fast-reid#320]
## Instructions To Reproduce the 🐛 Bug:
AssertionError: No evaluation results obtained during training!
1. what changes you made (`git diff`) or what code you wrote
```
Latest code, no change anything ,just --resume
pytorch==1.6
```
2. what exact command you run: python ./tools/train_net.py --config-file ./configs/DukeMTMC/sbs_R101-ibn.yml --resume MODEL.WEIGHTS logs/dukemtmc/sbs_R101-ibn/model_final.pth
3. what you observed (including __full logs__):
```
[10/22 10:53:48 fastreid.engine.defaults]: Freeze layer group "backbone" training for 27970 iterations
[10/22 10:53:48 fastreid.utils.checkpoint]: Loading checkpoint from logs/dukemtmc/sbs_R101-ibn/model_final.pth
[10/22 10:53:50 fastreid.utils.checkpoint]: Loading optimizer from logs/dukemtmc/sbs_R101-ibn/model_final.pth
[10/22 10:53:51 fastreid.utils.checkpoint]: Loading scheduler from logs/dukemtmc/sbs_R101-ibn/model_final.pth
[10/22 10:53:51 fastreid.engine.train_loop]: Starting training from iteration 167820
[10/22 10:53:51 fastreid.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "./tools/train_net.py", line 58, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 46, in main
    return trainer.train()
  File "./fastreid/engine/defaults.py", line 365, in train
    ), "No evaluation results obtained during training!"
AssertionError: No evaluation results obtained during training!

```

**Comment by zengwbz** [comment]
> ## Instructions To Reproduce the  Bug:
> AssertionError: No evaluation results obtained during training!
> 
> 1. what changes you made (`git diff`) or what code you wrote
> 
> ```
> Latest code, no change anything ,just --resume
> pytorch==1.6
> ```
> 
> 1. what exact command you run: python ./tools/train_net.py --config-file ./configs/DukeMTMC/sbs_R101-ibn.yml --resume MODEL.WEIGHTS logs/dukemtmc/sbs_R101-ibn/model_final.pth
> 2. what you observed (including **full logs**):
> 
> ```
> [10/22 10:53:48 fastreid.engine.defaults]: Freeze layer group "backbone" training for 27970 iterations
> [10/22 10:53:48 fastreid.utils.checkpoint]: Loading checkpoint from logs/dukemtmc/sbs_R101-ibn/model_final.pth
> [10/22 10:53:50 fastreid.utils.checkpoint]: Loading optimizer from logs/dukemtmc/sbs_R101-ibn/model_final.pth
> [10/22 10:53:51 fastreid.utils.checkpoint]: Loading scheduler from logs/dukemtmc/sbs_R101-ibn/model_final.pth
> [10/22 10:53:51 fastreid.engine.train_loop]: Starting training from iteration 167820
> [10/22 10:53:51 fastreid.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
> Traceback (most recent call last):
>   File "./tools/train_net.py", line 58, in <module>
>     args=(args,),
>   File "./fastreid/engine/launch.py", line 71, in launch
>     main_func(*args)
>   File "./tools/train_net.py", line 46, in main
>     return trainer.train()
>   File "./fastreid/engine/defaults.py", line 365, in train
>     ), "No evaluation results obtained during training!"
> AssertionError: No evaluation results obtained during training!
> ```

问题解决了，训练--resume时问题出在报这个错
AssertionError: Default process group is not initialized
如果训练启用了分布式训练相关的代码，如果不使用分布式训练，就不要启动syncBN。config改为BN 就好
