### ISSUE TITLE
AssertionError: No evaluation results obtained during training!

### ISSUE THREAD

**Issue by zhangguohui-git** [JDAI-CV/fast-reid#338]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
latest code, download latest market_sbs_R50 model,delete `PRETRAIN_PATH` 
```
2. what exact command you run:
```
python tools/train_net.py --config-file ./configs/Market1501/sbs_R50.yml MODEL.DEVICE "cuda:0"
```
3. what you observed (including __full logs__):
```
[11/11 17:04:10 fastreid.engine.defaults]: Freeze layer group "backbone" training for 2020 iterations
[11/11 17:04:10 fastreid.utils.checkpoint]: No checkpoint found. Training model from scratch
[11/11 17:04:10 fastreid.engine.train_loop]: Starting training from iteration 0
ERROR [11/11 17:04:11 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/home/zgh/reid/fast-reid-master/fastreid/engine/train_loop.py", line 125, in train
    self.run_step()
  File "/home/zgh/reid/fast-reid-master/fastreid/engine/train_loop.py", line 212, in run_step
    outs = self.model(data)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zgh/reid/fast-reid-master/fastreid/modeling/meta_arch/baseline.py", line 37, in forward
    features = self.backbone(images)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zgh/reid/fast-reid-master/fastreid/modeling/backbones/resnet.py", line 183, in forward
    x = self.maxpool(x)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/nn/modules/pooling.py", line 159, in forward
    self.return_indices)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/_jit_internal.py", line 247, in fn
    return if_false(*args, **kwargs)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/nn/functional.py", line 576, in _max_pool2d
    input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 1.96 GiB total capacity; 595.42 MiB already allocated; 37.38 MiB free; 610.00 MiB reserved in total by PyTorch)
[11/11 17:04:11 fastreid.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "tools/train_net.py", line 57, in <module>
    args=(args,),
  File "/home/zgh/reid/fast-reid-master/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "tools/train_net.py", line 45, in main
    return trainer.train()
  File "/home/zgh/reid/fast-reid-master/fastreid/engine/defaults.py", line 365, in train
    ), "No evaluation results obtained during training!"
AssertionError: No evaluation results obtained during training!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 25, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/multiprocessing/connection.py", line 498, in Client
    answer_challenge(c, authkey)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/multiprocessing/connection.py", line 742, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/zgh/anaconda3/envs/fastreid/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer

```

**Comment by L1aoXingyu** [comment]
Cuda out of memory, you can decrease batch size or image size to solve this problem.

**Comment by zhangguohui-git** [comment]
thank you,it'ok.

**Comment by zhangguohui-git** [comment]
thank you,it's ok.
