### ISSUE TITLE
cannot import name 'amp' from 'torch.cuda'

### ISSUE THREAD

**Issue by guanyonglai** [JDAI-CV/fast-reid#343]
https://github.com/JDAI-CV/fast-reid/blob/df823da09a1b24befbafd3bd3a5b938b7ef6de3f/fastreid/engine/train_loop.py#L211
I deleted the code related amp, but it raise:
Traceback (most recent call last):
  File "./fastreid/engine/train_loop.py", line 126, in train
    self.run_step()
  File "./fastreid/engine/train_loop.py", line 213, in run_step
    outs = self.model(data)
  File "/home/guanyonglai/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./fastreid/modeling/meta_arch/mgn.py", line 105, in forward
    b1_outputs = self.b1_head(b1_feat, targets)
  File "/home/guanyonglai/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./fastreid/modeling/heads/embedding_head.py", line 83, in forward
    cls_outputs = self.classifier(bn_feat, targets)
  File "/home/guanyonglai/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "./fastreid/layers/circle_softmax.py", line 38, in forward
    pred_class_logits = targets * s_p + (1.0 - targets) * s_n
RuntimeError: expected backend CUDA and dtype Float but got backend CUDA and dtype Lon

**Comment by gmt710** [comment]
pred_class_logits = targets.float() * s_p.float() + (1.0 - targets.float()) * s_n.float()

**Comment by guanyonglai** [comment]
thx

**Comment by guanyonglai** [comment]
装torch1.6也可以直接跑起来
