### ISSUE TITLE
设置FP16_ENABLED: True，出现cuda error

### ISSUE THREAD

**Issue by JiangZongKang** [JDAI-CV/fast-reid#407]
``python tools/train_net.py --config-file ./configs/Market1501/AGW_R50.yml MODEL.DEVICE "cuda:5"``

log:
ERROR [02/08 01:07:31 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "./fastreid/engine/train_loop.py", line 143, in train
    self.run_step()
  File "./fastreid/engine/defaults.py", line 385, in run_step
    self._trainer.run_step()
  File "./fastreid/engine/train_loop.py", line 324, in run_step
    self._write_metrics(loss_dict, data_time)
  File "./fastreid/engine/train_loop.py", line 267, in _write_metrics
    metrics_dict = {k: v.detach().cpu().item() for k, v in loss_dict.items()}
  File "./fastreid/engine/train_loop.py", line 267, in <dictcomp>
    metrics_dict = {k: v.detach().cpu().item() for k, v in loss_dict.items()}
  File "/opt/conda/envs/apex-test/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA error: an illegal memory access was encountered
[02/08 01:07:31 fastreid.engine.hooks]: Total training time: 0:00:01 (0:00:00 on hooks)
Traceback (most recent call last):
  File "tools/train_net.py", line 57, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "tools/train_net.py", line 45, in main
    return trainer.train()
  File "./fastreid/engine/defaults.py", line 376, in train
    super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
  File "./fastreid/engine/train_loop.py", line 143, in train
    self.run_step()
  File "./fastreid/engine/defaults.py", line 385, in run_step
    self._trainer.run_step()
  File "./fastreid/engine/train_loop.py", line 324, in run_step
    self._write_metrics(loss_dict, data_time)
  File "./fastreid/engine/train_loop.py", line 267, in _write_metrics
    metrics_dict = {k: v.detach().cpu().item() for k, v in loss_dict.items()}
  File "./fastreid/engine/train_loop.py", line 267, in <dictcomp>
    metrics_dict = {k: v.detach().cpu().item() for k, v in loss_dict.items()}
  File "/opt/conda/envs/apex-test/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA error: an illegal memory access was encountered

使用的是pytorch 1.7, cuda 10.1环境

@L1aoXingyu @lingxiao-he  @JinkaiZheng

**Comment by L1aoXingyu** [comment]
可以使用最新的代码再试试
