### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by sijun-zhou** [JDAI-CV/fast-reid#435]
Hi, 
I met the problem while training with market1501.
My environment:
2080ti: 2
cuda: 10.0
apex: 0.1
torch: 1.2.0
torchvision: 0.4.0

(fastreid) root@sj_docker1_117:/home/wesine/data_8tb_3/sj/work/reid/fast-reid $ cd /home/wesine/data_8tb_3/sj/work/reid/fast-reid ; env PYTHONIOENCODING=UTF-8 PYTHONUNBUFFERED=1 /root/anaconda3/envs/fastreid/bin/python /root/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py --default --nodebug --client --host localhost --port 46053 /home/wesine/data_8tb_3/sj/work/reid/fast-reid/tools/train_net.py --config-file ./configs/Market1501/sbs_R50-ibn.yml --num-gpus 2 
Command Line Args: Namespace(config_file='./configs/Market1501/sbs_R50-ibn.yml', dist_url='tcp://127.0.0.1:49152', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)
[03/18 18:27:01 fastreid]: Rank of current process: 0. World size: 2
[03/18 18:27:01 fastreid]: Environment info:
----------------------  -------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) [GCC 9.3.0]
numpy                   1.19.5
fastreid                1.0.0 @/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid
FASTREID_ENV_MODULE     <not set>
PyTorch                 1.2.0 @/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1                 GeForce RTX 2080 Ti
CUDA_HOME               /usr/local/cuda
Pillow                  8.1.2
torchvision             0.4.0 @/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
cv2                     4.5.1
----------------------  -------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.18.1 (Git Hash 7de7e5d02bf687f971e7668963649728356e0c20)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.2
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

[03/18 18:27:01 fastreid]: Command line arguments: Namespace(config_file='./configs/Market1501/sbs_R50-ibn.yml', dist_url='tcp://127.0.0.1:49152', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)
[03/18 18:27:01 fastreid]: Contents of args.config_file=./configs/Market1501/sbs_R50-ibn.yml:
_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    WITH_IBN: True

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: logs/market1501/sbs_R50-ibn

[03/18 18:27:01 fastreid]: Running with full config:
CUDNN_BENCHMARK: True
DATALOADER:
  NAIVE_WAY: True
  NUM_INSTANCE: 16
  NUM_WORKERS: 8
  PK_SAMPLER: True
DATASETS:
  COMBINEALL: False
  NAMES: ('Market1501',)
  TESTS: ('Market1501',)
INPUT:
  AUGMIX_PROB: 0.0
  AUTOAUG_PROB: 0.1
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: False
    HUE: 0.1
    PROB: 0.5
    SATURATION: 0.1
  DO_AFFINE: False
  DO_AUGMIX: False
  DO_AUTOAUG: True
  DO_FLIP: True
  DO_PAD: True
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: True
    PROB: 0.5
    VALUE: [123.675, 116.28, 103.53]
  RPT:
    ENABLED: False
    PROB: 0.5
  SIZE_TEST: [384, 128]
  SIZE_TRAIN: [384, 128]
KD:
  MODEL_CONFIG: ['']
  MODEL_WEIGHTS: ['']
MODEL:
  BACKBONE:
    DEPTH: 50x
    FEAT_DIM: 2048
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    PRETRAIN: True
    PRETRAIN_PATH: 
    WITH_IBN: True
    WITH_NL: True
    WITH_SE: False
  DEVICE: cuda
  FREEZE_LAYERS: ['backbone']
  HEADS:
    CLS_LAYER: circleSoftmax
    EMBEDDING_DIM: 0
    MARGIN: 0.35
    NAME: EmbeddingHead
    NECK_FEAT: after
    NORM: BN
    NUM_CLASSES: 0
    POOL_LAYER: gempoolP
    SCALE: 64
    WITH_BNNECK: True
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 1.0
    CIRCLE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    COSFACE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME: ('CrossEntropyLoss', 'TripletLoss')
    TRI:
      HARD_MINING: True
      MARGIN: 0.0
      NORM_FEAT: False
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.120000000000005, 57.375]
  QUEUE_SIZE: 8192
  WEIGHTS: 
OUTPUT_DIR: logs/market1501/sbs_R50-ibn
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 20
  DELAY_EPOCHS: 30
  ETA_MIN_LR: 7e-07
  FP16_ENABLED: False
  FREEZE_FC_ITERS: 0
  FREEZE_ITERS: 1000
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  MAX_EPOCH: 60
  MOMENTUM: 0.9
  NESTEROV: True
  OPT: Adam
  SCHED: CosineAnnealingLR
  STEPS: [40, 90]
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: False
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 10
  FLIP_ENABLED: False
  IMS_PER_BATCH: 128
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: False
    NUM_ITER: 300
  RERANK:
    ENABLED: False
    K1: 20
    K2: 6
    LAMBDA: 0.3
  ROC_ENABLED: False
[03/18 18:27:01 fastreid]: Full config saved to /home/wesine/data_8tb_3/sj/work/reid/fast-reid/logs/market1501/sbs_R50-ibn/config.yaml
[03/18 18:27:01 fastreid.utils.env]: Using a generated random seed 1895871
[03/18 18:27:01 fastreid.engine.defaults]: Prepare training set
[03/18 18:27:02 fastreid.data.datasets.bases]: => Loaded Market1501 in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| train    | 751     | 12936      | 6           |
[03/18 18:27:02 fastreid.engine.defaults]: Auto-scaling the num_classes=751
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "/root/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2020.2.64397/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/root/anaconda3/envs/fastreid/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/tools/train_net.py", line 57, in <module>
    args=(args,),
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/engine/launch.py", line 68, in launch
    daemon=False,
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/root/anaconda3/envs/fastreid/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/root/anaconda3/envs/fastreid/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/root/anaconda3/envs/fastreid/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/root/anaconda3/envs/fastreid/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/engine/launch.py", line 103, in _distributed_worker
    main_func(*args)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/engine/defaults.py", line 214, in __init__
    model = self.build_model(cfg)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/engine/defaults.py", line 395, in build_model
    model = build_model(cfg)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/modeling/meta_arch/build.py", line 24, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg, **kwargs)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/modeling/meta_arch/baseline.py", line 26, in __init__
    self.backbone = build_backbone(cfg)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/modeling/backbones/build.py", line 26, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/modeling/backbones/resnet.py", line 351, in build_resnet_backbone
    state_dict = init_pretrained_weights(key)
  File "/home/wesine/data_8tb_3/sj/work/reid/fast-reid/fastreid/modeling/backbones/resnet.py", line 282, in init_pretrained_weights
    gdown.download(model_urls[key], cached_file, quiet=False)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/gdown/download.py", line 110, in download
    res = sess.get(url, stream=True)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/envs/fastreid/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

Thanks in advance!

**Comment by twj1999** [comment]
Hi，what's the reason for this. i meet the same problem

**Comment by L1aoXingyu** [comment]
Maybe your server cannot connect to the Internet.
