### ISSUE TITLE
转TensorRT时报错

### ISSUE THREAD

**Issue by lichaomingAI** [JDAI-CV/fast-reid#438]
在当我用训练好的mgn模型转TensorRT时出现了以下错误，请问如何解决呢？谢谢。

fast-reid-master/tools/deploy$ python trt_export.py --name msmt_mgn_R50-ibn --output outputs/trt_model --mode fp32 --batch-size 8 --height 384 --width 128 --onnx-model /home/ubuntu/桌面/fast-reid-master/tools/deploy/outputs/onnx_model/msmt_mgn_R50-ibn.onnx 
[03/21 16:34:20 trt_export]: Loading ONNX file from path /home/ubuntu/桌面/fast-reid-master/tools/deploy/outputs/onnx_model/msmt_mgn_R50-ibn.onnx...
[03/21 16:34:20 trt_export]: Beginning ONNX file parsing
[03/21 16:34:20 trt_export]: Completed parsing of ONNX file.
[03/21 16:34:20 trt_export]: Building an engine from file /home/ubuntu/桌面/fast-reid-master/tools/deploy/outputs/onnx_model/msmt_mgn_R50-ibn.onnx; this may take a while...
[03/21 16:35:03 trt_export]: Create engine successfully!
[03/21 16:35:03 trt_export]: Saving TRT engine file to path outputs/trt_model/msmt_mgn_R50-ibn.engine
[TensorRT] ERROR: FAILED_ALLOCATION: basic_string::_S_construct null not valid
Traceback (most recent call last):
  File "trt_export.py", line 170, in <module>
    onnx2trt(onnx_file_path, engineFile, args.mode, int8_calibrator=int8_calib)
  File "trt_export.py", line 154, in onnx2trt
    f.write(engine.serialize())
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by gmt710** [comment]
MGN应该不支持转吧？

**Comment by lichaomingAI** [comment]
@gmt710 转应该是可以转的，这个报错好像是保存模型时出错的，即写不到保存文件中，我尝试不保存模型，直接用转完后的模型在内存内直接推理，是可以计算的，但我发现用的速度好慢，一张384×129的图片用了0.02秒左右。

**Comment by L1aoXingyu** [comment]
@lichaomingAI onnx 转成功了吗

**Comment by lichaomingAI** [comment]
@L1aoXingyu onnx转成功了，在onnxruntime上运行一张图片快了0.2-0.3秒左右，现在是想在TensorRT上运行，但我直接用TensorRT转出来的模型(没有保存)，运行一张图片需要0.02秒？这更慢了，不知道是不是有些东西没有释放还是怎样，TensorRT不太懂额。希望大神可以解决一下，非常感谢。

**Comment by lichaomingAI** [comment]
@L1aoXingyu 额是快了2-3ms，不好意思

**Comment by L1aoXingyu** [comment]
我没有转过 mgn，不过应该是可以转的，你可以先试试转不带 ibn 的模型

**Comment by lichaomingAI** [comment]
@L1aoXingyu 好的，我去试一下，感谢。

**Comment by young169** [comment]
mgn-ibn转tensorrt成功了，但是在inference的时候报错，貌似是tensorrt现在还不支持instance normalization?
