### ISSUE TITLE
onnx export with dynamic_axes

### ISSUE THREAD

**Issue by uefall** [JDAI-CV/fast-reid#455]
我准备把模型转ONNX-tensorRT，然后在TRITON中部署，需要在转ONNX时设置dynamic axes来支持动态batchsize，加入input_names,output_names,dynamic_axes三行的参数后，转换时报错。
是我哪里操作不对嘛？
```
/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py:182: UserWarning: ONNX export failed on max_pool2d because input size not accessible not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
```
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from outputs/onnx_model/agw_R50-ibn_container_dyna.onnx failed:Fatal error: max_pool2d is not a registered function/op
```

```python
    # Export the model to ONNX
    with torch.no_grad():
        with io.BytesIO() as f:
            torch.onnx.export(
                model,
                inputs,
                f,
                operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
                verbose=True,  # NOTE: uncomment this for debugging
                # export_params=True,
                input_names=['batch_input'],
                output_names=['feat'],
                dynamic_axes={'batch_input': {0: 'batch_size'},
                              'feat': {0: 'batch_size'}}
            )
            onnx_model = onnx.load_from_string(f.getvalue())
```

**Comment by uefall** [comment]
将resnet中的
```
self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, ceil_mode=True)
```
修改为ceil_mode=False
或者export参数改为
```python
operator_export_type=OperatorExportTypes.ONNX,
opset_version=10,
```
可以不出现max_pool2d的问题，但是出现了新的
```
Traceback (most recent call last):
  File "onnx_export.py", line 145, in <module>
    onnx_model = export_onnx_model(model, inputs)
  File "onnx_export.py", line 106, in export_onnx_model
    torch.onnx.export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 225, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 85, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 635, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 417, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 203, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/__init__.py", line 263, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 938, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 133, in wrapper
    return fn(g, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_opset9.py", line 553, in split
    size = self.type().sizes()[dim]
TypeError: 'NoneType' object is not subscriptable 
```
挠头……

**Comment by L1aoXingyu** [comment]
我还没试过转 dynamic batch，稍后我试试

**Comment by uefall** [comment]
现在我测试的结果是在自己的环境中可以转动态batchsize的onnx（torch 1.7.1+cu110）
在容器里中不行（nvcr.io/nvidia/pytorch:20.12-py3 torch 1.8.0a0+1606899）
可能是是pytorch版本的关系吧

转好之后在下一步到tensorRT还是有个IBN的支持问题要等21.04发布
参考: https://github.com/NVIDIA/TensorRT/issues/1183

这个issue我先关啦，多谢
