### ISSUE TITLE
demo/demo.py 运行出错

### ISSUE THREAD

**Issue by jiehui87** [JDAI-CV/fast-reid#469]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
<put diff or code here>
```
2. what exact command you run:
python -u demo/demo.py --config-file configs/DukeMTMC/sbs_R50-ibn.yml --input videocrop/*.jpg --output datasets --opts MODEL.WEIGHTS model/model_best.pth
3. what you observed (including __full logs__):
```
Traceback (most recent call last):
  File "demo/demo.py", line 85, in <module>
    feat = demo.run_on_image(img)
  File "/data2/zhangjiehui/fast-reid-master/demo/predictor.py", line 57, in run_on_image
    predictions = self.predictor(image)
  File "/data2/zhangjiehui/fast-reid-master/fastreid/engine/defaults.py", line 154, in __call__
    predictions = self.model(inputs)
  File "/home/stailb/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/zhangjiehui/fast-reid-master/fastreid/modeling/meta_arch/baseline.py", line 100, in forward
    images = self.preprocess_image(batched_inputs)
  File "/data2/zhangjiehui/fast-reid-master/fastreid/modeling/meta_arch/baseline.py", line 130, in preprocess_image
    images.sub_(self.pixel_mean).div_(self.pixel_std)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

```

**Comment by L1aoXingyu** [comment]
Try it again with latest code.
