### ISSUE TITLE
TypeError: adaptive_avg_pool2d() got an unexpected keyword argument 'ceil_mode'

### ISSUE THREAD

**Issue by GeLink9999** [JDAI-CV/fast-reid#475]
when i try to converts a fastreid model to Caffe format. I follow the tutorial step by step, when I run caffe_export.py to get the converted Caffe model. The issues are as follows. How should I do next? Than s

Traceback (most recent call last):
  File "caffe_export.py", line 83, in <module>
    pytorch_to_caffe.trans_net(model, inputs, args.name)
  File "/workspace/ShareData/fast-reid-master_1gpu/tools/deploy/pytorch_to_caffe.py", line 738, in trans_net
    out = net.forward(input_var)
  File "../../fastreid/modeling/meta_arch/baseline.py", line 116, in forward
    outputs = self.heads(features)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../../fastreid/modeling/heads/embedding_head.py", line 120, in forward
    pool_feat = self.pool_layer(features)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 1107, in forward
    return F.adaptive_avg_pool2d(input, self.output_size)
  File "/workspace/ShareData/fast-reid-master_1gpu/tools/deploy/pytorch_to_caffe.py", line 660, in __call__
    out = self.obj(self.raw, *args, **kwargs)
  File "/workspace/ShareData/fast-reid-master_1gpu/tools/deploy/pytorch_to_caffe.py", line 639, in _adaptive_avg_pool2d
    _pool('ave', raw, input, x, input.shape[2], input.shape[2], 0, False)
  File "/workspace/ShareData/fast-reid-master_1gpu/tools/deploy/pytorch_to_caffe.py", line 194, in _pool
    caffe_out = raw(input, kernel_size, stride, padding, ceil_mode=True)
TypeError: adaptive_avg_pool2d() got an unexpected keyword argument 'ceil_mode'

**Comment by L1aoXingyu** [comment]
Which model did you convert?

**Comment by GeLink9999** [comment]
I am using "python caffe_export.py". The model is the one generated by /tools/train.py in this fast-reid project.
Thanks

**Comment by GeLink9999** [comment]
Who can help me out? Thanks a lot.

**Comment by L1aoXingyu** [comment]
Add this line 
```
cfg.MODEL.HEADS.POOL_LAYER = "Identity"
```
in `tools/deploy/caffe_export.py`
![image](https://user-images.githubusercontent.com/19245504/116177346-3a253b80-a746-11eb-9115-2650ce7cc91f.png)

After converting the model, add the average pooling in the right place.

**Comment by GeLink9999** [comment]
> Add this line
> 
> ```
> cfg.MODEL.HEADS.POOL_LAYER = "Identity"
> ```
> 
> in `tools/deploy/caffe_export.py`
> ![image](https://user-images.githubusercontent.com/19245504/116177346-3a253b80-a746-11eb-9115-2650ce7cc91f.png)
> 
> After converting the model, add the average pooling in the right place.

That is so cool! it works. Thanks a lot.
