### ISSUE TITLE
Export ONNX failed:  module 'onnx' has no attribute 'optimizer'

### ISSUE THREAD

**Issue by 1224wxwx** [JDAI-CV/fast-reid#479]
When I tried to export ONNX model, I got following error: 

```
Traceback (most recent call last):
  File "onnx_export.py", line 134, in <module>
    onnx_model = export_onnx_model(model, inputs)
  File "onnx_export.py", line 113, in export_onnx_model
    all_passes = onnx.optimizer.get_available_passes()
AttributeError: module 'onnx' has no attribute 'optimizer'
```

My onnx version is "1.9.0". Could you please tell me which version do you use?

Thanks so much.

**Comment by L1aoXingyu** [comment]
Please use the latest code.
