### ISSUE TITLE
How to train models on CPU?

### ISSUE THREAD

**Issue by BenjaminQU259** [JDAI-CV/fast-reid#485]
Hi, I ran into some issues when trying to train the model on CPU. I use a computer with ubuntu and without GPU, so I have no choice but to use CPU.
After setting up environment and datasets, I ran the command as below:
```
python tools/train_net.py --config-file configs/Market1501/mgn_R50-ibn.yml MODEL.DEVICE "cpu"
```
And an error message displayed as:
```
Traceback (most recent call last):
  File "tools/train_net.py", line 51, in <module>
    launch(
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "./fastreid/engine/defaults.py", line 205, in __init__
    data_loader = self.build_train_loader(cfg)
  File "./fastreid/engine/defaults.py", line 416, in build_train_loader
    return build_reid_train_loader(cfg, combineall=cfg.DATASETS.COMBINEALL)
  File "./fastreid/config/config.py", line 265, in wrapped
    return orig_func(**explicit_args)
  File "./fastreid/data/build.py", line 88, in build_reid_train_loader
    train_loader = DataLoaderX(
  File "./fastreid/data/data_utils.py", line 147, in __init__
    self.stream = torch.cuda.Stream(local_rank)  # create a new cuda stream in each process
  File "/home/ubuntu/anaconda3/envs/fastreid/lib/python3.8/site-packages/torch/cuda/streams.py", line 28, in __new__
    with torch.cuda.device(device):
  File "/home/ubuntu/anaconda3/envs/fastreid/lib/python3.8/site-packages/torch/cuda/__init__.py", line 243, in __enter__
    self.prev_idx = torch._C._cuda_getDevice()
AttributeError: module 'torch._C' has no attribute '_cuda_getDevice'

```
I searched the internet but got no useful solutions. Could somebody help me please, thanks a lot!

P.S. It did show this though:
```
[05/12 12:07:36 fastreid]: Rank of current process: 0. World size: 1
[05/12 12:07:36 fastreid]: Environment info:
-------------------  -----------------------------------------------------------------------------------
sys.platform         linux
Python               3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
numpy                1.20.1
fastreid             1.3 @./fastreid
FASTREID_ENV_MODULE  <not set>
PyTorch              1.6.0 @/home/ubuntu/anaconda3/envs/fastreid/lib/python3.8/site-packages/torch
PyTorch debug build  False
GPU available        False
Pillow               8.2.0
torchvision          0.7.0 @/home/ubuntu/anaconda3/envs/fastreid/lib/python3.8/site-packages/torchvision
cv2                  4.5.2
-------------------  -----------------------------------------------------------------------------------
  ......
```

**Comment by L1aoXingyu** [comment]
I use cuda stream to accelerate data loading, so if you want to train with cpu, it will raise the error.
I will fix it later.

**Comment by BenjaminQU259** [comment]
> I use cuda stream to accelerate data loading, so if you want to train with cpu, it will raise the error.
> I will fix it later.

OK thanks!

**Comment by Shephermand** [comment]
Fix complete？
