### ISSUE TITLE
export to caffe failed, ModuleNotFoundError

### ISSUE THREAD

**Issue by Royzon** [JDAI-CV/fast-reid#495]
When I export my pytorch model to caffe model, I got bug as following:  
  
Traceback (most recent call last):
  File "caffe_export.py", line 22, in <module>
    from projects.bjzProject.projectbaseline import add_moco_config
ModuleNotFoundError: No module named 'projects.bjzProject'
  
I searched whole fast-reid projects, but I didn't find the function。

**Comment by L1aoXingyu** [comment]
Please use the latest code.

**Comment by Royzon** [comment]
ok. I used 1.0 version

**Comment by Royzon** [comment]
@L1aoXingyu  The latest code seems to be good, but in the process of convert caffe model, I encountered another problem:  

Traceback (most recent call last):
  File "tools/deploy/caffe_export.py", line 67, in <module>
    cfg = setup_cfg(args)
  File "tools/deploy/caffe_export.py", line 32, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/config/config.py", line 112, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/config/config.py", line 123, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/usr/anaconda3/envs/caffe_infer/lib/python3.6/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/usr/anaconda3/envs/caffe_infer/lib/python3.6/site-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/usr/anaconda3/envs/caffe_infer/lib/python3.6/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: INPUT.DO_AUTOAUG'

I don't know if this problem has anything to do with my trained model, so I  paste my model config here, please help me to have a look, thank you

_BASE_: Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_osnet_backbone
    DEPTH: x0_25
    FEAT_DIM: 128

INPUT:
  DO_AUTOAUG: True

OUTPUT_DIR: "logs/market1501/my_osnet"

**Comment by L1aoXingyu** [comment]
Because in the new version, some keywords in config have been changed, and you need to delete these keywords or change them.
In the above example, you need to change `INPUT.DO_AUTOAUG`.

**Comment by Royzon** [comment]
OK, Thank you very much for your kind answer.  I changed my osnetx0.25 config as follows and retrained the mdoel with latset master code: 
`
_BASE_: Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_osnet_backbone
    DEPTH: x0_25
    FEAT_DIM: 128

INPUT:
  AUTOAUG:
    ENABLED: True

OUTPUT_DIR: "logs/market1501/my_osnet"
`
But I got the error message：
Traceback (most recent call last):
  File "./tools/train_net.py", line 57, in <module>
    args=(args,),
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/engine/defaults.py", line 207, in __init__
    model = self.build_model(cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/engine/defaults.py", line 382, in build_model
    model = build_model(cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/modeling/meta_arch/build.py", line 24, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/config/config.py", line 245, in wrapped
    init_func(self, **explicit_args)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/modeling/meta_arch/baseline.py", line 53, in __init__
    self.register_buffer('pixel_mean', torch.Tensor(pixel_mean).view(1, -1, 1, 1), False)
TypeError: register_buffer() takes 3 positional arguments but 4 were given

I have to ask you what went wrong again?

**Comment by L1aoXingyu** [comment]
Please follow the instruction

## Instructions To Reproduce the Issue:

Check https://stackoverflow.com/help/minimal-reproducible-example for how to ask good questions.
Simplify the steps to reproduce the issue using suggestions from the above link, and provide them below:

1. full code you wrote or full changes you made (`git diff`)
```
<put code or diff here>
```
2. what exact command you run:
3. __full logs__ you observed:
```
<put logs here>
```

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

If you expect the model to converge / work better, note that we do not give suggestions
on how to train a new model.
Only in one of the two conditions we will help with it:
(1) You're unable to reproduce the results in fastreid model zoo.
(2) It indicates a fastreid bug.

**Comment by Royzon** [comment]
@L1aoXingyu I suspect that there may be bug in the latest osnet related code.  
1. changes  
   
![image](https://user-images.githubusercontent.com/36632724/119956507-bde77780-bfd3-11eb-8f42-2d4c0a06fd97.png)

2. command  
  python ./tools/train_net.py --config-file ./configs/Base-bagtricks.yml MODEL.DEVICE "cuda:0"

3. error logs
  Traceback (most recent call last):
  File "./tools/train_net.py", line 57, in <module>
    args=(args,),
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/engine/defaults.py", line 207, in __init__
    model = self.build_model(cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/engine/defaults.py", line 382, in build_model
    model = build_model(cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/modeling/meta_arch/build.py", line 24, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/config/config.py", line 245, in wrapped
    init_func(self, **explicit_args)
  File "/media/usr/40A0451FA0451D32/code/projects/fast-reid/fastreid/modeling/meta_arch/baseline.py", line 53, in __init__
    self.register_buffer('pixel_mean', torch.Tensor(pixel_mean).view(1, -1, 1, 1), False)
TypeError: register_buffer() takes 3 positional arguments but 4 were given

**Comment by L1aoXingyu** [comment]
Please paste the full training config in your model save directory, and its name is `config.yaml`.

**Comment by Royzon** [comment]
CUDNN_BENCHMARK: true
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  SAMPLER_TRAIN: NaiveIdentitySampler
  SET_WEIGHT: []
DATASETS:
  COMBINEALL: false
  NAMES:
  - Market1501
  TESTS:
  - Market1501
INPUT:
  AFFINE:
    ENABLED: false
  AUGMIX:
    ENABLED: false
    PROB: 0.0
  AUTOAUG:
    ENABLED: false
    PROB: 0.0
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.15
    ENABLED: false
    HUE: 0.1
    PROB: 0.5
    SATURATION: 0.1
  CROP:
    ENABLED: false
    RATIO:
    - 0.75
    - 1.3333333333333333
    SCALE:
    - 0.16
    - 1
    SIZE:
    - 224
    - 224
  FLIP:
    ENABLED: true
    PROB: 0.5
  PADDING:
    ENABLED: true
    MODE: constant
    SIZE: 10
  REA:
    ENABLED: true
    PROB: 0.5
    VALUE:
    - 123.675
    - 116.28
    - 103.53
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 256
  - 128
  SIZE_TRAIN:
  - 256
  - 128
KD:
  MODEL_CONFIG:
  - ''
  MODEL_WEIGHTS:
  - ''
MODEL:
  BACKBONE:
    DEPTH: x0_25
    FEAT_DIM: 128
    LAST_STRIDE: 1
    NAME: build_osnet_backbone
    NORM: BN
    PRETRAIN: false
    PRETRAIN_PATH: ''
    WITH_IBN: false
    WITH_NL: false
    WITH_SE: false
  DEVICE: cuda:0
  FREEZE_LAYERS:
  - ''
  HEADS:
    CLS_LAYER: Linear
    EMBEDDING_DIM: 0
    MARGIN: 0.0
    NAME: EmbeddingHead
    NECK_FEAT: before
    NORM: BN
    NUM_CLASSES: 751
    POOL_LAYER: GlobalAvgPool
    SCALE: 1
    WITH_BNNECK: true
  LOSSES:
    CE:
      ALPHA: 0.2
      EPSILON: 0.1
      SCALE: 1.0
    CIRCLE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    COSFACE:
      GAMMA: 128
      MARGIN: 0.25
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.3
      NORM_FEAT: false
      SCALE: 1.0
  META_ARCHITECTURE: Baseline
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  QUEUE_SIZE: 8192
  WEIGHTS: ''
OUTPUT_DIR: logs/
SOLVER:
  AMP:
    ENABLED: true
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2.0
  CHECKPOINT_PERIOD: 30
  DELAY_EPOCHS: 0
  ETA_MIN_LR: 1.0e-07
  FREEZE_FC_ITERS: 0
  FREEZE_ITERS: 0
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  MAX_EPOCH: 120
  MOMENTUM: 0.9
  NESTEROV: false
  OPT: Adam
  SCHED: MultiStepLR
  STEPS:
  - 40
  - 90
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 30
  FLIP:
    ENABLED: false
  IMS_PER_BATCH: 128
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3
  ROC:
    ENABLED: false

**Comment by L1aoXingyu** [comment]
Can you train with other backbones, such as resnet?

**Comment by Royzon** [comment]
yes, resnet backbone is ok.
