### ISSUE TITLE
eval-only veri-wild

### ISSUE THREAD

**Issue by daliel** [JDAI-CV/fast-reid#497]
my comand:
`python3 tools/plain_train_net.py --config-file ./configs/VERIWild/bagtricks_R50-ibn.yml --eval-only MODEL.WEIGHTS /media/daliel/hdd/fast-reid/datasets/VERI-Wild/veriwild_bot_R50-ibn.pth MODEL.DEVICE "cuda:0"`

i have error:
```
[05/27 14:34:45 fastreid.utils.checkpoint]: Loading checkpoint from /media/daliel/hdd/fast-reid/datasets/VERI-Wild/veriwild_bot_R50-ibn.pth
[05/27 14:35:01 fastreid.utils.checkpoint]: Some model parameters or buffers are not found in the checkpoint:
  heads.bnneck.{weight, bias, running_var, running_mean}
  heads.weight
[05/27 14:35:01 fastreid.utils.checkpoint]: The checkpoint state_dict contains keys that are not used by the model:
  pixel_mean
  pixel_std
  heads.bottleneck.0.{weight, bias, running_mean, running_var, num_batches_tracked}
  heads.classifier.weight
[05/27 14:35:01 fastreid]: Prepare testing set
[05/27 14:35:03 fastreid.data.datasets.bases]: => Loaded SmallVeRiWild in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 3000    | 3000       | 105         |
| gallery  | 3000    | 38861      | 146         |
[05/27 14:35:03 fastreid.evaluation.evaluator]: Start inference on 41861 images
Traceback (most recent call last):
  File "tools/plain_train_net.py", line 218, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "tools/plain_train_net.py", line 197, in main
    return do_test(cfg, model)
  File "tools/plain_train_net.py", line 53, in do_test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "./fastreid/evaluation/evaluator.py", line 126, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "./fastreid/evaluation/reid_evaluation.py", line 44, in process
    'camids': inputs['camids'].to(self._cpu_device)
AttributeError: 'list' object has no attribute 'to'
```

**Comment by TelBotDev** [comment]
I have met the same error in vehiclereid. I have fixed it [here](https://github.com/JDAI-CV/fast-reid/pull/511/commits/87caad14d806d30d8e25833657542b5afcaad99c).
