### ISSUE TITLE
AttributeError: module 'faiss' has no attribute 'cast_integer_to_long_ptr'

### ISSUE THREAD

**Issue by AlphaPlusTT** [JDAI-CV/fast-reid#498]
When i run the train_net.py in --eval-only mode with rerank enable, i got the error:
`
[05/28 16:15:42 fastreid.evaluation.evaluator]: Start inference on 19889 images
[05/28 16:15:50 fastreid.evaluation.evaluator]: Inference done 11/156. 0.5326 s / batch. ETA=0:01:21
[05/28 16:16:20 fastreid.evaluation.evaluator]: Inference done 64/156. 0.5372 s / batch. ETA=0:00:52
[05/28 16:16:50 fastreid.evaluation.evaluator]: Inference done 116/156. 0.5423 s / batch. ETA=0:00:22
[05/28 16:17:13 fastreid.evaluation.evaluator]: Total inference time: 0:01:26.502893 (0.572867 s / batch per device, on 1 devices)
[05/28 16:17:13 fastreid.evaluation.evaluator]: Total inference pure compute time: 0:01:22 (0.544687 s / batch per device, on 1 devices)
[05/28 16:17:17 fastreid.evaluation.reid_evaluation]: Test with rerank setting
Traceback (most recent call last):
  File "tools/train_net.py", line 57, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "tools/train_net.py", line 39, in main
    res = DefaultTrainer.test(cfg, model)
  File "./fastreid/engine/defaults.py", line 454, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "./fastreid/evaluation/evaluator.py", line 156, in inference_on_dataset
    results = evaluator.evaluate()
  File "./fastreid/evaluation/reid_evaluation.py", line 102, in evaluate
    rerank_dist = build_dist(query_features, gallery_features, metric="jaccard", k1=k1, k2=k2)
  File "/home/ccf/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "./fastreid/utils/compute_dist.py", line 53, in build_dist
    dist = compute_jaccard_distance(feat, k1=kwargs["k1"], k2=kwargs["k2"], search_option=0)
  File "/home/ccf/anaconda3/envs/fastreid/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "./fastreid/utils/compute_dist.py", line 78, in compute_jaccard_distance
    _, initial_rank = search_raw_array_pytorch(res, features, features, k1)
  File "./fastreid/utils/faiss_utils.py", line 87, in search_raw_array_pytorch
    I_ptr = swig_ptr_from_LongTensor(I)
  File "./fastreid/utils/faiss_utils.py", line 19, in swig_ptr_from_LongTensor
    return faiss.cast_integer_to_long_ptr(
AttributeError: module 'faiss' has no attribute 'cast_integer_to_long_ptr'
`

**Comment by L1aoXingyu** [comment]
Maybe your faiss version is wrong. Please install `faiss=1.7.0`.

**Comment by AlphaPlusTT** [comment]
I checked the version of `faiss` and it's 1.7.0

**Comment by L1aoXingyu** [comment]
Sorry, I checked it and found the faiss version is 1.6.3

**Comment by AlphaPlusTT** [comment]
yes, `faiss<=1.6.4` is fine

**Comment by berylyellow** [comment]
@L1aoXingyu @AlphaPlusTT 请问可以跑通的1.6.3版本是 faiss-gpu 还是 faiss-cpu？

**Comment by X-funbean** [comment]
If you're using faiss 1.7.0, you can go to `fastreid/utils/faiss_utisl.py` and replace 
```python
return faiss.cast_integer_to_long_ptr(
    x.storage().data_ptr() + x.storage_offset() * 8
)
```
with
```
return faiss.cast_integer_to_idx_t_ptr(
    x.storage().data_ptr() + x.storage_offset() * 8)
```
in function `swig_ptr_from_LongTensor()`

**Comment by gallardorafael** [comment]
Just to confirm: faiss<=1.6.4 solves the problem.

The problem is that the 'cast_integer_to_long_ptr' disappeared after 1.6.4.
