### ISSUE TITLE
train FastAttr market1501 error.

### ISSUE THREAD

**Issue by 5Yesterday** [JDAI-CV/fast-reid#510]
I just run "python3 projects/FastAttr/train_net.py --config-file projects/FastAttr/configs/market1501.yml --num-gpus 0"
Got this: 
Traceback (most recent call last):
  File "projects/FastAttr/train_net.py", line 125, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "projects/FastAttr/train_net.py", line 111, in main
    trainer = AttrTrainer(cfg)
  File "./fastreid/engine/defaults.py", line 203, in __init__
    model = self.build_model(cfg)
  File "projects/FastAttr/train_net.py", line 35, in build_model
    model = DefaultTrainer.build_model(cfg)
  File "./fastreid/engine/defaults.py", line 367, in build_model
    model = build_model(cfg)
  File "./fastreid/modeling/meta_arch/build.py", line 24, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "./fastreid/config/config.py", line 245, in wrapped
    init_func(self, **explicit_args)
  File "./fastreid/modeling/meta_arch/baseline.py", line 53, in __init__
    self.register_buffer('pixel_mean', torch.Tensor(pixel_mean).view(1, -1, 1, 1), False)
TypeError: register_buffer() takes 3 positional arguments but 4 were given
Thanks!

**Comment by L1aoXingyu** [comment]
Change `--num-gpus 0` to `--num-gpus 1`

**Comment by 5Yesterday** [comment]
@L1aoXingyu It's not that kind of mistake.

**Comment by L1aoXingyu** [comment]
Your pytorch version?

**Comment by 5Yesterday** [comment]
@L1aoXingyu 1.1.0

**Comment by 5Yesterday** [comment]
It must >=1.6?

**Comment by L1aoXingyu** [comment]
Yes.

**Comment by 5Yesterday** [comment]
It works.
