### ISSUE TITLE
convert pytorch model to caffe

### ISSUE THREAD

**Issue by weilli** [JDAI-CV/fast-reid#533]
139992753919104:add_blob16 getting
139992753919032:relu_blob49 getting
neck.pool_layer
ave_pool1 was added to layers
139992753919248:ave_pool_blob1 was added to blobs
Add blob     ave_pool_blob1    : torch.Size([1, 2048, 1, 1])
Traceback (most recent call last):
  File "caffe_export.py", line 277, in <module>
    pytorch_to_caffe.trans_net(mynet, inputs, args.name)
  File "/home/liwei/fast-reid/tools/deploy/pytorch_to_caffe.py", line 738, in trans_net
    out = net.forward(input_var)
  File "caffe_export.py", line 179, in forward
    x=self.neck(x)
  File "/home/liwei/anaconda3/envs/pytorch1.2.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "caffe_export.py", line 137, in forward
    global_feat = self.pool_layer(features)
  File "/home/liwei/anaconda3/envs/pytorch1.2.0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../../fastreid/layers/pooling.py", line 74, in forward
    return F.adaptive_avg_pool2d(x, self.output_size).pow(1. / self.p)
  File "/home/liwei/fast-reid/tools/deploy/pytorch_to_caffe.py", line 660, in __call__
    out = self.obj(self.raw, *args, **kwargs)
  File "/home/liwei/fast-reid/tools/deploy/pytorch_to_caffe.py", line 639, in _adaptive_avg_pool2d
    _pool('ave', raw, input, x, input.shape[2], input.shape[2], 0, False)
  File "/home/liwei/fast-reid/tools/deploy/pytorch_to_caffe.py", line 183, in _pool
    layer = caffe_net.Layer_param(name=layer_name, type='Pooling', bottom=[log.blobs(input)], top=top_blobs)
  File "/home/liwei/fast-reid/tools/deploy/pytorch_to_caffe.py", line 101, in blobs
    print("{}:{} getting".format(var, self._blobs[var]))
  File "/home/liwei/fast-reid/tools/deploy/pytorch_to_caffe.py", line 39, in __getitem__
    return self.data[key]
KeyError: 139992753919392
 
I used the GemP pooling. Is it caused this error?

**Comment by L1aoXingyu** [comment]
Yes, if you use GeM pooling, you need to assemble this layer with other layers.

**Comment by weilli** [comment]
> Yes, if you use GeM pooling, you need to assemble this layer with other layers.


Could you explain it in details? Thank you!

**Comment by L1aoXingyu** [comment]
GeM will do power(3), average pooing, sqrt(3), so you can split gem layer into 3 layers.
