### ISSUE TITLE
RuntimeError: All input tensors must be on the same device.

### ISSUE THREAD

**Issue by xiaosai666** [JDAI-CV/fast-reid#535]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
nothing
```
2. what exact command you run: 
python projects/FastAttr/train_net.py  --config-file projects/FastAttr/configs/pa100.yml  --num-gpus 4
3. what you observed (including __full logs__):
```
ERROR [07/23 17:45:25 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/root/cloud/xs2/gender_classfication/fast-reid/fastreid/engine/train_loop.py", line 148, in train
    self.after_epoch()
  File "/root/cloud/xs2/gender_classfication/fast-reid/fastreid/engine/train_loop.py", line 182, in after_epoch
    h.after_epoch()
  File "/root/cloud/xs2/gender_classfication/fast-reid/fastreid/engine/hooks.py", line 377, in after_epoch
    self._do_eval()
  File "/root/cloud/xs2/gender_classfication/fast-reid/fastreid/engine/hooks.py", line 351, in _do_eval
    results = self._func()
  File "/root/cloud/xs2/gender_classfication/fast-reid/fastreid/engine/defaults.py", line 303, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/root/cloud/xs2/gender_classfication/fast-reid/fastreid/engine/defaults.py", line 439, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "/root/cloud/xs2/gender_classfication/fast-reid/fastreid/evaluation/evaluator.py", line 156, in inference_on_dataset
    results = evaluator.evaluate()
  File "/root/cloud/xs2/gender_classfication/fast-reid/projects/FastAttr/fastattr/attr_evaluation.py", line 95, in evaluate
    gt_labels = torch.stack(gt_labels, dim=0).numpy()
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cuda:3
[07/23 17:45:25 fastreid.engine.hooks]: Overall training speed: 3118 iterations in 0:21:17 (0.4096 s / it)
[07/23 17:45:25 fastreid.engine.hooks]: Total training time: 0:21:58 (0:00:41 on hooks)
Traceback (most recent call last): 
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/reid/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/fast-reid/fastreid/engine/launch.py", line 103, in _distributed_worker
    main_func(*args)
  File "/fast-reid/projects/FastAttr/train_net.py", line 112, in main
    return trainer.train()
  File "/fast-reid/fastreid/engine/defaults.py", line 348, in train
    super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
  File "/fast-reid/fastreid/engine/train_loop.py", line 148, in train
    self.after_epoch()
  File "/fast-reid/fastreid/engine/train_loop.py", line 182, in after_epoch
    h.after_epoch()
  File "/fast-reid/fastreid/engine/hooks.py", line 377, in after_epoch
    self._do_eval()
  File "/fast-reid/fastreid/engine/hooks.py", line 351, in _do_eval
    results = self._func()
  File "/fast-reid/fastreid/engine/defaults.py", line 303, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/fast-reid/fastreid/engine/defaults.py", line 439, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "/fast-reid/fastreid/evaluation/evaluator.py", line 156, in inference_on_dataset
    results = evaluator.evaluate()
  File "/fast-reid/projects/FastAttr/fastattr/attr_evaluation.py", line 95, in evaluate
    gt_labels = torch.stack(gt_labels, dim=0).numpy()
RuntimeError: All input tensors must be on the same device. Received cuda:0 and cuda:3
```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

If there are no obvious error in "what you observed" provided above,
please tell us the expected behavior.

## Environment:
py3.7 torch1.8

**Comment by L1aoXingyu** [comment]
You can follow here
https://github.com/JDAI-CV/fast-reid/blob/7e652fea2ac76db27170ce8ab294724ddfe8b716/fastreid/evaluation/reid_evaluation.py#L42

Change the process in attribute evaluation
https://github.com/JDAI-CV/fast-reid/blob/7e652fea2ac76db27170ce8ab294724ddfe8b716/projects/FastAttr/fastattr/attr_evaluation.py#L32

**Comment by xiaosai666** [comment]
thx!
