### ISSUE TITLE
训练VeRi-Wild数据集时出现KeyError:"000001"错误

### ISSUE THREAD

**Issue by 17802592576** [JDAI-CV/fast-reid#536]
发生错误的日志是这样的，猜测是初始化camid时出错，但是看了代码之后没发现错误，如果有大佬知道的话，请告诉我一下，十分感谢

[07/25 08:27:32 fastreid]: Full config saved to /home/zhz/ll/code/reid/fast-reid/logs/veriwild/bagtricks_R50-ibn_4gpu/config.yaml
[07/25 08:27:32 fastreid.utils.env]: Using a generated random seed 32670587
[07/25 08:27:32 fastreid.engine.defaults]: Prepare training set
Traceback (most recent call last):
  File "tools/train_net.py", line 57, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "./fastreid/engine/defaults.py", line 201, in __init__
    data_loader = self.build_train_loader(cfg)
  File "./fastreid/engine/defaults.py", line 400, in build_train_loader
    return build_reid_train_loader(cfg, combineall=cfg.DATASETS.COMBINEALL)
  File "./fastreid/config/config.py", line 264, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "./fastreid/config/config.py", line 292, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "./fastreid/data/build.py", line 36, in _train_loader_from_config
    data = DATASET_REGISTRY.get(d)(root=_root, **kwargs)
  File "./fastreid/data/datasets/veriwild.py", line 53, in __init__
    train = self.process_dir(self.train_list)
  File "./fastreid/data/datasets/veriwild.py", line 67, in process_dir
    camid = int(self.imgid2camid[imgid])
KeyError: '000001'

**Comment by L1aoXingyu** [comment]
可能是你的数据集有问题

**Comment by gallardorafael** [comment]
If your vehicle_info.txt does not have the header, then the code is trying to avoid the first row of that file, so you never register the image '000001". I coded a workaround, just change the following function on the file 'fastreid/data/datasets/veriwild.py': 

```
    def process_vehicle(self, vehicle_info):
        imgid2vid = {}
        imgid2camid = {}
        imgid2imgpath = {}
        vehicle_info_lines = open(vehicle_info, 'r').readlines()

        #for idx, line in enumerate(vehicle_info_lines[1:]):
        for idx, line in enumerate(vehicle_info_lines):
            vid = line.strip().split('/')[0]
            imgid = line.strip().split(';')[0].split('/')[1]
            camid = line.strip().split(';')[1]
            img_path = osp.join(self.image_dir, vid, imgid + '.jpg')
            imgid2vid[imgid] = vid
            imgid2camid[imgid] = camid
            imgid2imgpath[imgid] = img_path

        #assert len(imgid2vid) == len(vehicle_info_lines) - 1
        assert len(imgid2vid) == len(vehicle_info_lines)
        return imgid2vid, imgid2camid, imgid2imgpath
```

Hope it works for you!
