### ISSUE TITLE
train time

### ISSUE THREAD

**Issue by alicera** [JDAI-CV/fast-reid#539]
If using 4 gpus, how much time does the network spend?

**Comment by L1aoXingyu** [comment]
Which dataset are you using?

**Comment by alicera** [comment]
data veri 

Do you know how to add the data to veri?

**Comment by L1aoXingyu** [comment]
It depends on your hardware. 
You can check here to add your own dataset.
https://github.com/JDAI-CV/fast-reid/issues/220

**Comment by alicera** [comment]
I add the some data to market1501.
But it still show the same image number 12936.

My method
This is the market1501 name rule   0001_c1s1_000151_01.jpg
I add some images and name it 1600_c1s1_000001_01.jpg , 1601_c1s1_000001_01.jpg ...
Then I put them to bounding_box_train folder.
Is it correct process?

**Comment by L1aoXingyu** [comment]
You can check whether this function can parse your image names?
https://github.com/JDAI-CV/fast-reid/blob/7e652fea2ac76db27170ce8ab294724ddfe8b716/fastreid/data/datasets/market1501.py#L72

**Comment by alicera** [comment]
I meet another problem

```
[08/10 07:38:44 fastreid.engine.defaults]: Prepare training set
/opt/conda/lib/python3.8/site-packages/torchvision/transforms/transforms.py:280: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train_net.py", line 51, in <module>
    launch(
  File "/work/Pictures/REID/fast-reid/./fastreid/engine/launch.py", line 64, in launch
    mp.spawn(
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/work/Pictures/REID/fast-reid/./fastreid/engine/launch.py", line 103, in _distributed_worker
    main_func(*args)
  File "/work/Pictures/REID/fast-reid/tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "/work/Pictures/REID/fast-reid/./fastreid/engine/defaults.py", line 201, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/work/Pictures/REID/fast-reid/./fastreid/engine/defaults.py", line 400, in build_train_loader
    return build_reid_train_loader(cfg, combineall=cfg.DATASETS.COMBINEALL)
  File "/work/Pictures/REID/fast-reid/./fastreid/config/config.py", line 264, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/work/Pictures/REID/fast-reid/./fastreid/config/config.py", line 292, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/work/Pictures/REID/fast-reid/./fastreid/data/build.py", line 42, in _train_loader_from_config
    data = DATASET_REGISTRY.get(d)(root=_root, **kwargs)
  File "/work/Pictures/REID/fast-reid/./fastreid/data/datasets/market1501.py", line 70, in __init__
    super(Market1501, self).__init__(train, query, gallery, **kwargs)
  File "/work/Pictures/REID/fast-reid/./fastreid/data/datasets/bases.py", line 47, in __init__
    self.data = self.train
  File "/work/Pictures/REID/fast-reid/./fastreid/data/datasets/bases.py", line 59, in train
    self._train = self._train()
  File "/work/Pictures/REID/fast-reid/./fastreid/data/datasets/market1501.py", line 65, in <lambda>
    train = lambda: self.process_dir(self.train_dir)
  File "/work/Pictures/REID/fast-reid/./fastreid/data/datasets/market1501.py", line 81, in process_dir
    assert 0 <= pid <= 1501  # pid == 0 means background
AssertionError

```
