### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by alicera** [JDAI-CV/fast-reid#541]
pytorch '1.9.0+cu102'
python tools/train_net.py --config-file ./configs/VeRi/sbs_R50-ibn.yml --num-gpus 4

07/30 11:41:40 fastreid.engine.hooks]: Open layer group "backbone" training
[07/30 11:42:39 fastreid.utils.events]:  eta: 0:46:32  epoch/iter: 14/3199  total_loss: 42.13  loss_cls: 42.13  loss_triplet: 0  time: 0.2903  data_time: 0.0060  lr: 9.98e-03  max_mem: 6056M
[07/30 11:42:42 fastreid.utils.events]:  eta: 0:46:30  epoch/iter: 14/3209  total_loss: 40.07  loss_cls: 40.07  loss_triplet: 0  time: 0.2903  data_time: 0.0051  lr: 9.98e-03  max_mem: 6056M
ERROR [07/30 11:42:46 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "./fastreid/engine/train_loop.py", line 145, in train
    self.run_step()
  File "./fastreid/engine/defaults.py", line 357, in run_step
    self._trainer.run_step()
  File "./fastreid/engine/train_loop.py", line 349, in run_step
    self._write_metrics(loss_dict, data_time)
  File "./fastreid/engine/train_loop.py", line 294, in _write_metrics
    raise FloatingPointError(
FloatingPointError: Loss became infinite or NaN at iteration=3223!
loss_dict = {'loss_cls': nan, 'loss_triplet': nan}
[07/30 11:42:46 fastreid.engine.hooks]: Overall training speed: 3221 iterations in 0:15:35 (0.2904 s / it)
[07/30 11:42:46 fastreid.engine.hooks]: Total training time: 0:16:10 (0:00:35 on hooks)
Traceback (most recent call last):
  File "tools/train_net.py", line 51, in <module>
    launch(
  File "./fastreid/engine/launch.py", line 64, in launch
    mp.spawn(
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "./fastreid/engine/launch.py", line 103, in _distributed_worker
    main_func(*args)
  File "/work/Pictures/REID/fast-reid/tools/train_net.py", line 45, in main
    return trainer.train()
  File "./fastreid/engine/defaults.py", line 348, in train
    super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
  File "./fastreid/engine/train_loop.py", line 145, in train
    self.run_step()
  File "./fastreid/engine/defaults.py", line 357, in run_step
    self._trainer.run_step()
  File "./fastreid/engine/train_loop.py", line 349, in run_step
    self._write_metrics(loss_dict, data_time)
  File "./fastreid/engine/train_loop.py", line 294, in _write_metrics
    raise FloatingPointError(
FloatingPointError: Loss became infinite or NaN at iteration=3223!
loss_dict = {'loss_cls': nan, 'loss_triplet': nan}

**Comment by L1aoXingyu** [comment]
If you train with 4GPUs, you need to change the batch size to 256.

**Comment by alicera** [comment]
I change the batch and it happen another error

[08/02 07:35:17 fastreid.utils.events]:  eta: 2:48:57  epoch/iter: 8/1763  total_loss: 32.41  loss_cls: 24.61  loss_triplet: 7.794  time: 0.9984  data_time: 0.0017  lr: 6.27e-03  max_mem: 6127M
[08/02 07:35:56 fastreid.utils.events]:  eta: 2:48:34  epoch/iter: 9/1799  total_loss: 32.02  loss_cls: 24.5  loss_triplet: 7.545  time: 1.0002  data_time: 0.0015  lr: 6.38e-03  max_mem: 6127M
[08/02 07:38:41 fastreid.engine.defaults]: Prepare testing set
/opt/conda/lib/python3.8/site-packages/torchvision/transforms/transforms.py:280: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/torchvision/transforms/transforms.py:280: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/torchvision/transforms/transforms.py:280: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
[08/02 07:38:43 fastreid.data.datasets.bases]: => Loaded VeRi in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 200     | 1678       | 19          |
| gallery  | 200     | 11579      | 19          |
[08/02 07:38:43 fastreid.evaluation.evaluator]: Start inference on 13257 images
Traceback (most recent call last):
  File "tools/train_net.py", line 51, in <module>
    launch(
  File "/work/Pictures/REID/fast-reid/./fastreid/engine/launch.py", line 64, in launch
    mp.spawn(
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 1 terminated with signal SIGKILL
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/conda/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
    self = reduction.pickle.load(from_parent)
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
_pickle.UnpicklingError: pickle data was truncated
_pickle.UnpicklingError: pickle data was truncated
/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 148 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by L1aoXingyu** [comment]
There is something wrong in testing.

**Comment by alicera** [comment]
I test it on 3 GPU, it will be show the error
But test it on 2 GPU, it work fine.

**Comment by L1aoXingyu** [comment]
We suggest using GPUs with an even number.

**Comment by alicera** [comment]
Got it. But I still meet the error when using 2 GPUs


max_mem: 6223M
[08/02 11:27:30 fastreid.utils.events]:  eta: 2:39:16  epoch/iter: 28/8554  total_loss: 6.306  loss_cls: 6.105  loss_triplet: 0.1602  time: 1.0136  data_time: 0.0013  lr: 9.98e-03  max_mem: 6223M
[08/02 11:28:17 fastreid.utils.events]:  eta: 2:38:40  epoch/iter: 29/8599  total_loss: 6.291  loss_cls: 6.079  loss_triplet: 0.1587  time: 1.0138  data_time: 0.0011  lr: 9.98e-03  max_mem: 6223M
[08/02 11:31:53 fastreid.utils.events]:  eta: 2:36:07  epoch/iter: 29/8799  total_loss: 6.087  loss_cls: 5.948  loss_triplet: 0.1525  time: 1.0152  data_time: 0.0013  lr: 9.98e-03  max_mem: 6223M
[08/02 11:32:47 fastreid.engine.defaults]: Prepare testing set
[08/02 11:32:48 fastreid.data.datasets.bases]: => Loaded VeRi in csv format: 
| subset   | # ids   | # images   | # cameras   |
|:---------|:--------|:-----------|:------------|
| query    | 200     | 1678       | 19          |
| gallery  | 200     | 11579      | 19          |
[08/02 11:32:48 fastreid.evaluation.evaluator]: Start inference on 13257 images
Traceback (most recent call last):
  File "tools/train_net.py", line 51, in <module>
    launch(
  File "/work/Pictures/REID/fast-reid/./fastreid/engine/launch.py", line 64, in launch
    mp.spawn(
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 130, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with signal SIGKILL
/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 104 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by L1aoXingyu** [comment]
Maybe it's out of memory.
