### ISSUE TITLE
resume

### ISSUE THREAD

**Issue by alicera** [JDAI-CV/fast-reid#543]
python tools/train_net.py --config-file ./configs/VeRi/sbs_R50-ibn.yml --num-gpus 2 --resume logs/veri/sbs_R50-ibn/model_best.pt

Traceback (most recent call last):
  File "tools/train_net.py", line 51, in <module>
    launch(
  File "/work/Pictures/REID/fast-reid/./fastreid/engine/launch.py", line 64, in launch
    mp.spawn(
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/work/Pictures/REID/fast-reid/./fastreid/engine/launch.py", line 103, in _distributed_worker
    main_func(*args)
  File "/work/Pictures/REID/fast-reid/tools/train_net.py", line 30, in main
    cfg = setup(args)
  File "/work/Pictures/REID/fast-reid/tools/train_net.py", line 23, in setup
    cfg.merge_from_list(args.opts)
  File "/work/Pictures/REID/fast-reid/./fastreid/config/config.py", line 134, in merge_from_list
    return super().merge_from_list(cfg_list)
  File "/opt/conda/lib/python3.8/site-packages/yacs/config.py", line 223, in merge_from_list
    _assert_with_logging(
  File "/opt/conda/lib/python3.8/site-packages/yacs/config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Override list has odd length: ['logs/veri/sbs_R50-ibn/model_best.pth']; it must be a list of pairs

**Comment by L1aoXingyu** [comment]
Resume means your training is interrupted, and want to train from the latest checkpoint. You can just add `--resume` flag not specifying model.pth.
If you want to load the trained model, you can set it like this `MODEL.WEIGHTS logs/.../model.pth`, then it will load the model automatically.

**Comment by alicera** [comment]
You can just add --resume flag not specifying model.pth.
How to find the pth that I interest？

**Comment by L1aoXingyu** [comment]
You can check `last_checkpoint` in your save directory.

**Comment by ming132** [comment]
nice
