### ISSUE TITLE
Exception: process 0 terminated with signal SIGKILL

### ISSUE THREAD

**Issue by deep-practice** [JDAI-CV/fast-reid#578]
[09/24 15:16:01 fastreid.evaluation.evaluator]: Start inference on 138517 images
[09/24 15:16:10 fastreid.evaluation.evaluator]: Inference done 11/2165. 0.0576 s / batch. ETA=0:02:26
[09/24 15:16:40 fastreid.evaluation.evaluator]: Inference done 422/2165. 0.0580 s / batch. ETA=0:02:07
[09/24 15:17:10 fastreid.evaluation.evaluator]: Inference done 832/2165. 0.0583 s / batch. ETA=0:01:37
[09/24 15:17:40 fastreid.evaluation.evaluator]: Inference done 1269/2165. 0.0584 s / batch. ETA=0:01:04
[09/24 15:18:10 fastreid.evaluation.evaluator]: Inference done 1741/2165. 0.0585 s / batch. ETA=0:00:29
[09/24 15:18:38 fastreid.evaluation.evaluator]: Total inference time: 0:02:28.507300 (0.068753 s / batch per device, on 2 devices)
[09/24 15:18:38 fastreid.evaluation.evaluator]: Total inference pure compute time: 0:02:06 (0.058631 s / batch per device, on 2 devices)
Traceback (most recent call last):
  File "tools/train_net.py", line 57, in <module>
    args=(args,),
  File "/home/work/deep_learning/local/fast-reid/fastreid/engine/launch.py", line 68, in launch
    daemon=False,
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 107, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGKILL
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 32 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 52 leaked semaphores to clean up at shutdown
  len(cache))

**Comment by L1aoXingyu** [comment]
It seems RAM out of memory when testing.

**Comment by deep-practice** [comment]
It runs smoothly when using one gpu

**Comment by ignasi00** [comment]
> It runs smoothly when using one gpu


I found that pyTorch datasets have memory leakage when using Distribuited Data Parallel if the dataset data is in lists.
And I tried to undestand what is happening in FastReId.
<br>

<ins>"SIMPLE" DESCRIPON OF FastReID</ins>

But FastReId store lists of pathes (strings) that can not be put in a tensor/ndarray.
[EDITED AFTERWARDS]: In fact, this happens in a pseudo Dataset from FastReId itself (not pyTorch Dataset), it is used in the Sampler in order to load from a real Dataset created afterwards.

Later this strings are loaded within their DataLoaderX when iter is called (creation of a iterable object).
DataLoaderX is an inheritance of pyTorch DataLoader.
The first step uses pyTorch (loading the pathes as an iterable object) and then loads a queue of **images**. This loading step generates a new daemon thread of hard-wired lenght 10.
Finally, there is a "preload" that make the process wait until there is an input available.

BUT: read_image? When is the data really read? The warpper "_train_loader_from_config" of "build_reid_train_loader" creates the real pyTorch Dataset object that FastReId wrote: CommDataset. This Dataset stores the strings lists, the data augmentation/transforms object and a bool flag. And when it is used, it reads the images that the sampler that uses the previous dataset yielded. CommDataset does not store loaded images (although it yields them).
<br>

So, although CommDataset loads images, DataLoaderX is the only place that stores images (in a thread! Search and see BackgroundGenerator).
I don't know if it is due to stack copies, pyTorch problems, garbage collection, or the queue.Queue object (still searching) **but 
in [https://bugs.python.org/issue43911](url) it seems that queue.Queue leaks and other queues like PriorityQueue and LifoQueue don't do it.**

(I will try it as soon as possible)
<br>

Anyways, I would appreciate a solution if anyone found a solution to this problem.
Thank you :)

**Comment by ignasi00** [comment]
LifoQueue is not a solution because the None that states the end will discard data in a LIFO case...

a self.queue.task_done() before the raise StopIteration may be better...

**Comment by ignasi00** [comment]
With LifoQueue it seems that the training works without leaks.
But the None as last item trick makes a LIFO queue a bad option, it allows discarding QUEUE_LEN-1 samples.

I also read somewhere that some C compilations can be recompiled with a "specific" option so it does not leak anymore (I don't know which ones or how to recompile them).
