### ISSUE TITLE
CUDA Error when using NVIDIA A10 GPU - Pytorch does not support A10G  ( with solution)

### ISSUE THREAD

**Issue by levipereira** [JDAI-CV/fast-reid#601]
We are Training VERI-Wild Dataset using FAST-REID. 
We build fast-reid docker image using this [Dockerfile ](https://github.com/JDAI-CV/fast-reid/blob/master/docker/Dockerfile).

The command:
```
python3 tools/train_net.py --config-file  ./configs/VERIWild/bagtricks_R50-ibn.yml  --num-gpus 4
```
Raise this error:
```
-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "./fastreid/engine/launch.py", line 89, in _distributed_worker
    comm.synchronize()
  File "./fastreid/utils/comm.py", line 78, in synchronize
    dist.barrier()
  File "/home/appuser/.local/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1710, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:32, unhandled cuda error, NCCL version 2.4.8
```
```
Traceback (most recent call last):
  File "tools/train_net.py", line 57, in <module>
    args=(args,),
  File "./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "./fastreid/engine/defaults.py", line 204, in __init__
    optimizer, param_wrapper = self.build_optimizer(cfg, model)
  File "./fastreid/engine/defaults.py", line 380, in build_optimizer
    return build_optimizer(cfg, model)
  File "./fastreid/solver/build.py", line 193, in build_optimizer
    params = ContiguousParams(params)
  File "./fastreid/utils/params.py", line 23, in __init__
    self._init_buffers()
  File "./fastreid/utils/params.py", line 49, in _init_buffers
    self._param_buffer.append(torch.zeros(size, dtype=dtype, device=device))
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
``` 
NVIDIA A10G with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA A10G GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```

After upgrade to latest Pytorch the error was raised:

```
Traceback (most recent call last):
  File "tools/train_net.py", line 13, in <module>
    from fastreid.engine import DefaultTrainer, default_argument_parser, default_setup, launch
  File "./fastreid/engine/__init__.py", line 14, in <module>
    from .defaults import *
  File "./fastreid/engine/defaults.py", line 23, in <module>
    from fastreid.modeling.meta_arch import build_model
  File "./fastreid/modeling/__init__.py", line 8, in <module>
    from .backbones import (
  File "./fastreid/modeling/backbones/__init__.py", line 16, in <module>
    from .mobilenetv3 import build_mobilenetv3_backbone
  File "./fastreid/modeling/backbones/mobilenetv3.py", line 7, in <module>
        from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'
``` 
Fix:
Upgrade to cuda 13 and cudnn 8
Use  latest Pytorch  compiled with cuda 13
```
FROM nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
	python3-opencv ca-certificates python3-dev git wget sudo ninja-build
RUN ln -sv /usr/bin/python3 /usr/bin/python

# create a non-root user
ARG USER_ID=1000
RUN useradd -m --no-log-init --system  --uid ${USER_ID} appuser -g sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER appuser
WORKDIR /home/appuser

ENV PATH="/home/appuser/.local/bin:${PATH}"
RUN wget https://bootstrap.pypa.io/get-pip.py && \
	python3 get-pip.py --user && \
	rm get-pip.py

# install dependencies
# See https://pytorch.org/ for other options if you use a different version of CUDA
RUN pip install --user tensorboard cmake   # cmake from apt-get is too old
## NOT WORKING TORCH WITH A10G
#RUN pip install --user torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/cu101/torch_stable.html
## WORKING TORCH WITH A10G
RUN pip install --user --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

RUN pip install --user -i https://pypi.tuna.tsinghua.edu.cn/simple tensorboard opencv-python cython yacs termcolor scikit-learn tabulate gdown gpustat faiss-gpu ipdb h5py
RUN sudo apt-get update && sudo apt-get install -y vim
```

To fix this :
```
ModuleNotFoundError: No module named 'torchvision.models.utils'
```

Change the [line ](https://github.com/JDAI-CV/fast-reid/blob/9208930c11ca26a8a92255a5323e979d9eb68282/fastreid/modeling/backbones/mobilenetv3.py#L7): 

to: 
```
try:
    from torch.hub import load_state_dict_from_url
except ImportError:
    from torch.utils.model_zoo import load_url as load_state_dict_from_url
```

Output:

```
[11/25 15:25:05 fastreid]: Environment info:
----------------------  --------------------------------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
numpy                   1.19.5
fastreid                1.3 @./fastreid
FASTREID_ENV_MODULE     <not set>
PyTorch                 1.11.0.dev20211125+cu113 @/home/appuser/.local/lib/python3.6/site-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0,1,2,3             NVIDIA A10G
CUDA_HOME               None
Pillow                  8.4.0
torchvision             0.12.0.dev20211125+cu113 @/home/appuser/.local/lib/python3.6/site-packages/torchvision
torchvision arch flags  /home/appuser/.local/lib/python3.6/site-packages/torchvision/_C.so
cv2                     4.5.4
----------------------  --------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

[11/25 15:25:05 fastreid]: Command line arguments: Namespace(config_file='./configs/VERIWild/bagtricks_R50-ibn.yml', dist_url='tcp://127.0.0.1:50152', eval_only=False, machine_rank=0, num_gpus=4, num_machines=1, opts=[], resume=False)
[11/25 15:25:05 fastreid]: Contents of args.config_file=./configs/VERIWild/bagtricks_R50-ibn.yml:
_BASE_: ../Base-bagtricks.yml
.
.
.
[11/25 15:30:23 fastreid.utils.events]:  eta: 8:17:14  epoch/iter: 1/599  total_loss: 9.807  loss_cls: 9.634  loss_triplet: 0.1958  time: 0.4668  data_time: 0.0055  lr: 7.25e-05  max_mem: 13591M
[11/25 15:31:58 fastreid.utils.events]:  eta: 8:12:08  epoch/iter: 1/799  total_loss: 9.195  loss_cls: 9.061  loss_triplet: 0.1441  time: 0.4638  data_time: 0.0078  lr: 8.51e-05  max_mem: 13591M
[11/25 15:33:34 fastreid.utils.events]:  eta: 8:09:44  epoch/iter: 1/999  total_loss: 6.907  loss_cls: 6.775  loss_triplet: 0.1224  time: 0.4635  data_time: 0.0077  lr: 9.77e-05  max_mem: 13591M
[11/25 15:34:16 fastreid.utils.events]:  eta: 8:08:41  epoch/iter: 1/1083  total_loss: 8.54  loss_cls: 8.433  loss_triplet: 0.1138  time: 0.4642  data_time: 0.0105  lr: 1.03e-04  max_mem: 13591M
[11/25 15:35:11 fastreid.utils.events]:  eta: 8:06:19  epoch/iter: 2/1199  total_loss: 8.277  loss_cls: 8.176  loss_triplet: 0.09906  time: 0.4638  data_time: 0.0089  lr: 1.10e-04  max_mem: 13591
```

**Comment by sunotsue** [comment]
reopening - have you found a fix?

**Comment by creativesalam** [comment]
Any update on this? Pytorch 1.6 works with CUDA 10.2 but latest GPUs work with CUDA>=11, anyone worked it out?

**Comment by levipereira** [comment]
read all https://github.com/JDAI-CV/fast-reid/issues/601#issue-1063866065 post. The workaround is on the post.
