### ISSUE TITLE
“FileNotFoundError: [Errno 2] No such file or directory: ' '”

### ISSUE THREAD

**Issue by huajiangY** [JDAI-CV/fast-reid#604]
## Instructions To Reproduce the 🐛 Bug:
We have configured the environment and downloaded the data set according to the tips inside，However, an error will be reported during operation “FileNotFoundError: [Errno 2] No such file or directory: ' '”.

**Comment by L1aoXingyu** [comment]
Please provide your command line and your dataset path.

**Comment by huajiangY** [comment]
I use it in window10 environment，I run train_net directly with the pycharm compiler, I didn't use other run instructions. My dataset path "C:\Users\ASUS\Desktop\reid\fast-reid-master\datasets"

**Comment by L1aoXingyu** [comment]
Please provide the complete error information.

**Comment by huajiangY** [comment]
D:\Users\ASUS\Anaconda3\envs\fastreid\python.exe C:/Users/ASUS/Desktop/reid/fast-reid-master/tools/train_net.py
Command Line Args: Namespace(config_file='', dist_url='tcp://127.0.0.1:49153', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "C:/Users/ASUS/Desktop/reid/fast-reid-master/tools/train_net.py", line 66, in <module>
    args=(args,),
  File "C:\Users\ASUS\Desktop\reid\fast-reid-master\fastreid\engine\launch.py", line 71, in launch
    main_func(*args)
  File "C:/Users/ASUS/Desktop/reid/fast-reid-master/tools/train_net.py", line 38, in main
    cfg = setup(args)
  File "C:/Users/ASUS/Desktop/reid/fast-reid-master/tools/train_net.py", line 30, in setup
    cfg.merge_from_file(args.config_file)
  File "C:\Users\ASUS\Desktop\reid\fast-reid-master\fastreid\config\config.py", line 112, in merge_from_file
    cfg_filename, allow_unsafe=allow_unsafe
  File "C:\Users\ASUS\Desktop\reid\fast-reid-master\fastreid\config\config.py", line 53, in load_yaml_with_base
    with PathManager.open(filename, "r") as f:
  File "C:\Users\ASUS\Desktop\reid\fast-reid-master\fastreid\utils\file_io.py", line 357, in open
    path, mode, buffering=buffering, **kwargs
  File "C:\Users\ASUS\Desktop\reid\fast-reid-master\fastreid\utils\file_io.py", line 251, in _open
    opener=opener,
FileNotFoundError: [Errno 2] No such file or directory: ''

Process finished with exit code 1

**Comment by L1aoXingyu** [comment]
You'd better use command line not pycharm launching.

**Comment by huajiangY** [comment]
OK, I'll try

**Comment by huajiangY** [comment]
I used "python tools/train_net.py --config-file ./configs/Market1501/bagtricks_R50.yml MODEL.DEVICE "cuda:0" "  
 and  I met a new problem: UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 119: illegal multibyte sequence
