### ISSUE TITLE
RuntimeError: "datasets/vehicleid/image" is not found

### ISSUE THREAD

**Issue by changgongcheng** [JDAI-CV/fast-reid#610]
12/09 14:47:22 fastreid]: Full config saved to /home/jiuling/zc/fast-reid/logs/vehicleid/bagtricks_R50-ibn_4gpu/config.yaml
[12/09 14:47:22 fastreid.utils.env]: Using a generated random seed 25863578
[12/09 14:47:22 fastreid.engine.defaults]: Prepare training set
Traceback (most recent call last):
  File "./tools/train_net.py", line 52, in <module>
    launch(
  File "/home/jiuling/zc/fast-reid/./fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "./tools/train_net.py", line 42, in main
    trainer = DefaultTrainer(cfg)
  File "/home/jiuling/zc/fast-reid/./fastreid/engine/defaults.py", line 201, in __init__
    data_loader = self.build_train_loader(cfg)
  File "/home/jiuling/zc/fast-reid/./fastreid/engine/defaults.py", line 400, in build_train_loader
    return build_reid_train_loader(cfg, combineall=cfg.DATASETS.COMBINEALL)
  File "/home/jiuling/zc/fast-reid/./fastreid/config/config.py", line 264, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/home/jiuling/zc/fast-reid/./fastreid/config/config.py", line 292, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/jiuling/zc/fast-reid/./fastreid/data/build.py", line 37, in _train_loader_from_config
    data = DATASET_REGISTRY.get(d)(root=_root, **kwargs)
  File "/home/jiuling/zc/fast-reid/./fastreid/data/datasets/vehicleid.py", line 46, in __init__
    self.check_before_run(required_files)
  File "/home/jiuling/zc/fast-reid/./fastreid/data/datasets/bases.py", line 139, in check_before_run
    raise RuntimeError('"{}" is not found'.format(fpath))
RuntimeError: "datasets/vehicleid/image" is not found

**Comment by changgongcheng** [comment]
my dataset path:
datasets/vehicleid/train
datasets/vehicleid/test

**Comment by changgongcheng** [comment]
why datasets/vehicleid/image?
