### ISSUE TITLE
KeyError: 'Non-existent config key: INPUT.REA.MEAN'

### ISSUE THREAD

**Issue by niangea** [JDAI-CV/fast-reid#619]
当我在用fastreid的时候，报了以下错误
Traceback (most recent call last):
  File "deepsort.py", line 178, in <module>
    with VideoTracker(cfg, args, video_path=args.VIDEO_PATH) as vdo_trk:
  File "deepsort.py", line 43, in __init__
    self.deepsort = build_tracker(cfg, use_cuda=use_cuda)
  File "/home/lihenian/mytest-01/deep_sort_pytorch-master/deep_sort/__init__.py", line 9, in build_tracker
    return DeepSort(model_path=cfg.FASTREID.CHECKPOINT, model_config=cfg.FASTREID.CFG, 
  File "/home/lihenian/mytest-01/deep_sort_pytorch-master/deep_sort/deep_sort.py", line 28, in __init__
    self.extractor = FastReIDExtractor(model_config, model_path, use_cuda=use_cuda)
  File "/home/lihenian/mytest-01/deep_sort_pytorch-master/deep_sort/deep/feature_extractor.py", line 55, in __init__
    cfg.merge_from_file(model_config)
  File "/home/lihenian/anaconda3/lib/python3.8/site-packages/fastreid/config/config.py", line 119, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/lihenian/anaconda3/lib/python3.8/site-packages/fastreid/config/config.py", line 130, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/lihenian/anaconda3/lib/python3.8/site-packages/yacs/config.py", line 225, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/lihenian/anaconda3/lib/python3.8/site-packages/yacs/config.py", line 493, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/lihenian/anaconda3/lib/python3.8/site-packages/yacs/config.py", line 493, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/lihenian/anaconda3/lib/python3.8/site-packages/yacs/config.py", line 506, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: INPUT.REA.MEAN'
请问有大佬知道是什么问题吗

**Comment by L1aoXingyu** [comment]
`REA.MEAN` 这个 key 已经没有了，现在 REA 相关的 key 在这里
https://github.com/JDAI-CV/fast-reid/blob/31d99b793fe0937461b9c9bc8a8a11f88bf5642c/fastreid/config/defaults.py#L189-L191

**Comment by niangea** [comment]
大佬方便拉下我进微信群吗？git上我添加了那个微信但是还没有进群


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JDAI-CV/fast-reid"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月3日(星期一) 下午5:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JDAI-CV/fast-reid] KeyError: 'Non-existent config key: INPUT.REA.MEAN' (Issue #619)





 
REA.MEAN 这个 key 已经没有了，现在 REA 相关的 key 在这里
 https://github.com/JDAI-CV/fast-reid/blob/31d99b793fe0937461b9c9bc8a8a11f88bf5642c/fastreid/config/defaults.py#L189-L191
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
