### ISSUE TITLE
No module named 'torch.utils.tensorboard'

### ISSUE THREAD

**Issue by fangwudi** [JDAI-CV/fast-reid#70]
error: No module named 'torch.utils.tensorboard'

my env:
pytorch 1.0.0
tensorboard:         1.12.2-py36he6710b0_0     
tensorflow:          1.12.0-gpu_py36he68c306_0 
tensorflow-base:     1.12.0-gpu_py36h8e0ae2d_0 
tensorflow-gpu:      1.12.0-h0d30ee6_0        

track back:
Traceback (most recent call last):
  File "tools/train_net.py", line 16, in <module>
    from fastreid.engine import DefaultTrainer, default_argument_parser, default_setup
  File "./fastreid/engine/__init__.py", line 13, in <module>
    from .hooks import *
  File "./fastreid/engine/hooks.py", line 17, in <module>
    from fastreid.solver import optim
  File "./fastreid/solver/__init__.py", line 8, in <module>
    from .build import build_lr_scheduler, build_optimizer
  File "./fastreid/solver/build.py", line 8, in <module>
    from . import optim
  File "./fastreid/solver/optim/__init__.py", line 1, in <module>
    from .lamb import Lamb
  File "./fastreid/solver/optim/lamb.py", line 9, in <module>
    from torch.utils.tensorboard import SummaryWriter
ModuleNotFoundError: No module named 'torch.utils.tensorboard'

**Comment by L1aoXingyu** [comment]
please update pytorch version to 1.1+

**Comment by fangwudi** [comment]
> please update pytorch version to 1.1+

ok, thanks. please update your install requirement

**Comment by L1aoXingyu** [comment]
thanks, I will update it soon.

**Comment by tb2-sy** [comment]
It does not work while the version of pytorch is 1.6.0，what can I do for this？thanks
