### ISSUE TITLE
RuntimeError: DataLoader worker exited unexpectedly during inference

### ISSUE THREAD

**Issue by jayong-sv** [JDAI-CV/fast-reid#737]
I encountered a problem during the inference phase using the `fast-reid` framework, where the process abruptly stops with the following error message:

```
RuntimeError: DataLoader worker (pid(s) 1255292, 1255293, 1255294, 1255295) exited unexpectedly
```

I haven't made any other changes besides integrating Weight & Biases into the existing main branch code, and I assume Weight & Biases is the cause of the issue.

The full traceback is provided below:

```
Traceback (most recent call last):
  File "/tmp/fast-reid/tools/omega_trainer.py", line 129, in <module>
    launch(
  File "/tmp/fast-reid/fastreid/engine/launch.py", line 71, in launch
    main_func(*args)
  File "/tmp/fast-reid/tools/omega_trainer.py", line 120, in main
    omega_train(
  File "/tmp/fast-reid/tools/omega_trainer.py", line 64, in omega_train
    return trainer.train()
  File "/tmp/fast-reid/fastreid/engine/defaults.py", line 359, in train
    super().train(self.start_epoch, self.max_epoch, self.iters_per_epoch)
  File "/tmp/fast-reid/fastreid/engine/train_loop.py", line 156, in train
    self.after_epoch()
  File "/tmp/fast-reid/fastreid/engine/train_loop.py", line 213, in after_epoch
    h.after_epoch()
  File "/tmp/fast-reid/fastreid/engine/hooks.py", line 377, in after_epoch
    self._do_eval()
  File "/tmp/fast-reid/fastreid/engine/hooks.py", line 351, in _do_eval
    results = self._func()
  File "/tmp/fast-reid/fastreid/engine/defaults.py", line 314, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "/tmp/fast-reid/fastreid/engine/defaults.py", line 450, in test
    results_i = inference_on_dataset(model, data_loader, evaluator, flip_test=cfg.TEST.FLIP.ENABLED)
  File "/tmp/fast-reid/fastreid/evaluation/evaluator.py", line 111, in inference_on_dataset
    for idx, inputs in enumerate(data_loader):
  File "/tmp/fast-reid/fastreid/data/data_utils.py", line 196, in __next__
    self.preload()
  File "/tmp/fast-reid/fastreid/data/data_utils.py", line 179, in preload
    self.batch = next(self.iter, None)
  File "/tmp/fast-reid/fastreid/data/data_utils.py", line 142, in __next__
    return self.next()
  File "/tmp/fast-reid/fastreid/data/data_utils.py", line 135, in next
    next_item = self.queue.get()
  File "/home/team/.pyenv/versions/3.8.10/lib/python3.8/queue.py", line 170, in get
    self.not_empty.wait()
  File "/home/team/.pyenv/versions/3.8.10/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
wandb: Waiting for W&B process to finish... (failed 255). Press Control-C to abort syncing.
Exception in thread Thread-134:
Traceback (most recent call last):
  File "/home/team/.pyenv/versions/reid/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1132, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/team/.pyenv/versions/3.8.10/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty
```

This issue seems to occur during the inference process, specifically when using the `inference_on_dataset` function. The DataLoader workers exit unexpectedly, causing the entire process to halt. This is consistently reproducible under the current setup.

**Environment**:
- Python version: 3.8.10
- fast-reid version: latest from the `main` branch
- OS: Ubuntu 20.04
- Hardware: NVIDIA 3090

**Comment by jayong-sv** [comment]
I set num_workers=0 [here](https://github.com/JDAI-CV/fast-reid/blob/c9bc3ceb2f7a6438b62fb515ea3df6d1e999e95d/fastreid/data/build.py#L131) and it works fine
