### ISSUE TITLE
训练需要多大的显存呀？这里8G显存不够，有最低要求吗？

### ISSUE THREAD

**Issue by LoryMANG** [JDAI-CV/fast-reid#92]

**Comment by L1aoXingyu** [comment]
11G 应该才行，你可以试试把 input size 改成 128x256，另外去掉 non-local， `WITH_NL=False`

**Comment by finger-monkey** [comment]
无法指定用某个GPU训练吗？

**Comment by finger-monkey** [comment]
请问训练过程中前几轮训练得好好的之后遇到如下问题，是内存引起的吗？
[06/09 05:01:27] fastreid.engine.defaults INFO: Evaluation results for Market1501 in csv format:
[06/09 05:01:27] fastreid.evaluation.testing INFO: Task: Rank-1
[06/09 05:01:27] fastreid.evaluation.testing INFO: 42.6%
[06/09 05:01:27] fastreid.evaluation.testing INFO: Task: Rank-5
[06/09 05:01:27] fastreid.evaluation.testing INFO: 61.8%
[06/09 05:01:27] fastreid.evaluation.testing INFO: Task: Rank-10
[06/09 05:01:27] fastreid.evaluation.testing INFO: 71.2%
[06/09 05:01:27] fastreid.evaluation.testing INFO: Task: mAP
[06/09 05:01:27] fastreid.evaluation.testing INFO: 19.6%
[06/09 05:01:27] fastreid.evaluation.testing INFO: Task: mINP
[06/09 05:01:27] fastreid.evaluation.testing INFO: 2.8%
[06/09 05:01:27] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.0001
[06/09 05:01:27] fastreid.evaluation.testing INFO: 3.1%
[06/09 05:01:27] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.001
[06/09 05:01:27] fastreid.evaluation.testing INFO: 11.2%
[06/09 05:01:27] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.01
[06/09 05:01:27] fastreid.evaluation.testing INFO: 34.1%
[06/09 05:01:28] fastreid.utils.events INFO: eta: 4:42:38  iter: 7999  total_loss: 43.895  loss_cls: 42.571  loss_triplet: 1.300  time: 1.6047  data_time: 0.0034  lr: 3.50e-04  max_mem: 6348M
.......
[06/09 05:47:32] fastreid.utils.events INFO: eta: 3:24:50  iter: 9799  total_loss: 33.780  loss_cls: 32.533  loss_triplet: 1.257  time: 1.5918  data_time: 0.0040  lr: 3.43e-04  max_mem: 6348M
[06/09 05:52:32] fastreid.engine.defaults INFO: prepare test set
[06/09 05:52:33] fastreid.data.datasets.bases INFO: => Loaded Market1501
[06/09 05:52:33] fastreid.data.datasets.bases INFO:   ----------------------------------------
[06/09 05:52:33] fastreid.data.datasets.bases INFO:   subset   | # ids | # images | # cameras
[06/09 05:52:33] fastreid.data.datasets.bases INFO:   ----------------------------------------
[06/09 05:52:33] fastreid.data.datasets.bases INFO:   query    |   750 |     3368 |         6
[06/09 05:52:33] fastreid.data.datasets.bases INFO:   gallery  |   751 |    15913 |         6
[06/09 05:52:33] fastreid.data.datasets.bases INFO:   ----------------------------------------
[06/09 05:52:33] fastreid.evaluation.evaluator INFO: Start inference on 19281 images
[06/09 05:52:50] fastreid.evaluation.evaluator INFO: Inference done 11/76. 0.6706 s / img. ETA=0:00:45
[06/09 05:53:20] fastreid.evaluation.evaluator INFO: Inference done 44/76. 0.8165 s / img. ETA=0:00:28
[06/09 05:53:51] fastreid.evaluation.evaluator INFO: Total inference time: 0:01:04.957465 (0.914894 s / img per device)
[06/09 05:53:51] fastreid.evaluation.evaluator INFO: Total inference pure compute time: 0:00:59 (0.842424 s / img per device)
[06/09 05:59:10] fastreid.engine.train_loop ERROR: Exception during training:
Traceback (most recent call last):
  File "./fastreid/engine/train_loop.py", line 122, in train
    self.after_step()
  File "./fastreid/engine/train_loop.py", line 142, in after_step
    h.after_step()
  File "./fastreid/engine/hooks.py", line 341, in after_step
    self._do_eval()
  File "./fastreid/engine/hooks.py", line 314, in _do_eval
    results = self._func()
  File "./fastreid/engine/defaults.py", line 311, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "./fastreid/engine/defaults.py", line 452, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "./fastreid/evaluation/evaluator.py", line 150, in inference_on_dataset
    results = evaluator.evaluate()
  File "./fastreid/evaluation/reid_evaluation.py", line 100, in evaluate
    tprs = evaluate_roc(dist, query_pids, gallery_pids, query_camids, gallery_camids)
  File "./fastreid/evaluation/roc.py", line 47, in evaluate_roc
    fpr, tpr, thresholds = metrics.roc_curve(labels, scores)
  File "/home/GYP/anaconda3/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 622, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/GYP/anaconda3/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 402, in _binary_clf_curve
    assert_all_finite(y_score)
  File "/home/GYP/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in assert_all_finite
    _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
  File "/home/GYP/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

**Comment by L1aoXingyu** [comment]
> 无法指定用某个GPU训练吗？

可以用CUDA_VISIBLE_DEVICES＝0 来指定gpu

**Comment by L1aoXingyu** [comment]
> 请问训练过程中前几轮训练得好好的之后遇到如下问题，是内存引起的吗？
> 
> [06/09 05:01:27] fastreid.engine.defaults INFO: Evaluation results for Market1501 in csv format:
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: Task: Rank-1
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: 42.6%
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: Task: Rank-5
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: 61.8%
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: Task: Rank-10
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: 71.2%
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: Task: mAP
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: 19.6%
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: Task: mINP
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: 2.8%
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.0001
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: 3.1%
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.001
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: 11.2%
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: Task: TPR@FPR=0.01
> 
> [06/09 05:01:27] fastreid.evaluation.testing INFO: 34.1%
> 
> [06/09 05:01:28] fastreid.utils.events INFO: eta: 4:42:38  iter: 7999  total_loss: 43.895  loss_cls: 42.571  loss_triplet: 1.300  time: 1.6047  data_time: 0.0034  lr: 3.50e-04  max_mem: 6348M
> 
> .......
> 
> [06/09 05:47:32] fastreid.utils.events INFO: eta: 3:24:50  iter: 9799  total_loss: 33.780  loss_cls: 32.533  loss_triplet: 1.257  time: 1.5918  data_time: 0.0040  lr: 3.43e-04  max_mem: 6348M
> 
> [06/09 05:52:32] fastreid.engine.defaults INFO: prepare test set
> 
> [06/09 05:52:33] fastreid.data.datasets.bases INFO: => Loaded Market1501
> 
> [06/09 05:52:33] fastreid.data.datasets.bases INFO:   ----------------------------------------
> 
> [06/09 05:52:33] fastreid.data.datasets.bases INFO:   subset   | # ids | # images | # cameras
> 
> [06/09 05:52:33] fastreid.data.datasets.bases INFO:   ----------------------------------------
> 
> [06/09 05:52:33] fastreid.data.datasets.bases INFO:   query    |   750 |     3368 |         6
> 
> [06/09 05:52:33] fastreid.data.datasets.bases INFO:   gallery  |   751 |    15913 |         6
> 
> [06/09 05:52:33] fastreid.data.datasets.bases INFO:   ----------------------------------------
> 
> [06/09 05:52:33] fastreid.evaluation.evaluator INFO: Start inference on 19281 images
> 
> [06/09 05:52:50] fastreid.evaluation.evaluator INFO: Inference done 11/76. 0.6706 s / img. ETA=0:00:45
> 
> [06/09 05:53:20] fastreid.evaluation.evaluator INFO: Inference done 44/76. 0.8165 s / img. ETA=0:00:28
> 
> [06/09 05:53:51] fastreid.evaluation.evaluator INFO: Total inference time: 0:01:04.957465 (0.914894 s / img per device)
> 
> [06/09 05:53:51] fastreid.evaluation.evaluator INFO: Total inference pure compute time: 0:00:59 (0.842424 s / img per device)
> 
> [06/09 05:59:10] fastreid.engine.train_loop ERROR: Exception during training:
> 
> Traceback (most recent call last):
> 
>   File "./fastreid/engine/train_loop.py", line 122, in train
> 
>     self.after_step()
> 
>   File "./fastreid/engine/train_loop.py", line 142, in after_step
> 
>     h.after_step()
> 
>   File "./fastreid/engine/hooks.py", line 341, in after_step
> 
>     self._do_eval()
> 
>   File "./fastreid/engine/hooks.py", line 314, in _do_eval
> 
>     results = self._func()
> 
>   File "./fastreid/engine/defaults.py", line 311, in test_and_save_results
> 
>     self._last_eval_results = self.test(self.cfg, self.model)
> 
>   File "./fastreid/engine/defaults.py", line 452, in test
> 
>     results_i = inference_on_dataset(model, data_loader, evaluator)
> 
>   File "./fastreid/evaluation/evaluator.py", line 150, in inference_on_dataset
> 
>     results = evaluator.evaluate()
> 
>   File "./fastreid/evaluation/reid_evaluation.py", line 100, in evaluate
> 
>     tprs = evaluate_roc(dist, query_pids, gallery_pids, query_camids, gallery_camids)
> 
>   File "./fastreid/evaluation/roc.py", line 47, in evaluate_roc
> 
>     fpr, tpr, thresholds = metrics.roc_curve(labels, scores)
> 
>   File "/home/anaconda3/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 622, in roc_curve
> 
>     y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
> 
>   File "/home/anaconda3/lib/python3.7/site-packages/sklearn/metrics/ranking.py", line 402, in _binary_clf_curve
> 
>     assert_all_finite(y_score)
> 
>   File "/home/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in assert_all_finite
> 
>     _assert_all_finite(X.data if sp.issparse(X) else X, allow_nan)
> 
>   File "/home/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
> 
>     raise ValueError(msg_err.format(type_err, X.dtype))
> 
> ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

请把你的配置文件发出来，在你的output_dir里面有一个config.yaml

**Comment by finger-monkey** [comment]
> > 请问训练过程中前几轮训练得好好的之后遇到如下问题，是内存引起的吗？
> > raise ValueError(msg_err.format(type_err, X.dtype))
> > ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
>


> 请把你的配置文件发出来，在你的output_dir里面有一个config.yaml
CUDNN_BENCHMARK: true
DATALOADER:
  NUM_INSTANCE: 16
  NUM_WORKERS: 16
  PK_SAMPLER: true
DATASETS:
  COMBINEALL: false
  NAMES:
  - Market1501
  TESTS:
  - Market1501
INPUT:
  DO_AUGMIX: false
  DO_AUTOAUG: true
  DO_CJ: false
  DO_FLIP: true
  DO_PAD: true
  FLIP_PROB: 0.5
  PADDING: 10
  PADDING_MODE: constant
  REA:
    ENABLED: true
    MEAN:
    - 123.675
    - 116.28
    - 103.53
    PROB: 0.5
  RPT:
    ENABLED: false
    PROB: 0.5
  SIZE_TEST:
  - 384
  - 128
  SIZE_TRAIN:
  - 384
  - 128
MODEL:
  BACKBONE:
    DEPTH: 101
    LAST_STRIDE: 1
    NAME: build_resnet_backbone
    NORM: BN
    NORM_SPLIT: 1
    PRETRAIN: true
    PRETRAIN_PATH: /home/GYP/code/fast-reid-master/models/resnet101_ibn_a.pth.tar
    WITH_IBN: true
    WITH_NL: true
    WITH_SE: false
  HEADS:
    CLS_LAYER: circle
    IN_FEAT: 2048
    MARGIN: 0.35
    NAME: BNneckHead
    NECK_FEAT: after
    NORM: BN
    NORM_SPLIT: 1
    NUM_CLASSES: 751
    POOL_LAYER: gempool
    REDUCTION_DIM: 512
    SCALE: 64
  LOSSES:
    CE:
      ALPHA: 0.3
      EPSILON: 0.1
      SCALE: 1.0
    FL:
      ALPHA: 0.25
      GAMMA: 2
      SCALE: 1.0
    NAME:
    - CrossEntropyLoss
    - TripletLoss
    TRI:
      HARD_MINING: true
      MARGIN: 0.0
      NORM_FEAT: false
      SCALE: 1.0
      USE_COSINE_DIST: false
  META_ARCHITECTURE: Baseline
  OPEN_LAYERS:
  - heads
  PIXEL_MEAN:
  - 123.675
  - 116.28
  - 103.53
  PIXEL_STD:
  - 58.395
  - 57.120000000000005
  - 57.375
  WEIGHTS: ''
OUTPUT_DIR: /home/GYP/code/fast-reid-master/logs_log/market_sbs_R101-ibn
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 6000
  DELAY_ITERS: 9000
  ETA_MIN_LR: 7.7e-07
  FREEZE_ITERS: 2000
  GAMMA: 0.1
  HEADS_LR_FACTOR: 1.0
  IMS_PER_BATCH: 64
  LOG_PERIOD: 200
  MAX_ITER: 18000
  MOMENTUM: 0.9
  OPT: Adam
  SCHED: DelayedCosineAnnealingLR
  STEPS:
  - 30
  - 55
  SWA:
    ENABLED: false
    ETA_MIN_LR: 3.5e-06
    ITER: 0
    LR_FACTOR: 10.0
    LR_SCHED: false
    PERIOD: 10
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 2000
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: false
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 256
  METRIC: cosine
  PRECISE_BN:
    DATASET: Market1501
    ENABLED: false
    NUM_ITER: 300
  RERANK:
    ENABLED: false
    K1: 20
    K2: 6
    LAMBDA: 0.3

**Comment by L1aoXingyu** [comment]
你可以先在这里把计算 ROC 注释掉，再试试看
https://github.com/JDAI-CV/fast-reid/blob/6ee38cd5627a328c9a3d52dd6f62166d68e1cf3e/fastreid/evaluation/reid_evaluation.py#L100

**Comment by finger-monkey** [comment]
> > 无法指定用某个GPU训练吗？
> 
> 可以用CUDA_VISIBLE_DEVICES＝0 来指定gpu

配置系统里似乎并没有这个参数可以用哦

**Comment by L1aoXingyu** [comment]
> > > 无法指定用某个GPU训练吗？
> > 
> > 
> > 可以用CUDA_VISIBLE_DEVICES＝0 来指定gpu
> 
> 配置系统里似乎并没有这个参数可以用哦

参考这样的写法
`CUDA_VISIBLE_DEVICES='0,1,2,3' python3 projects/PartialReID/train_net.py --config-file 'projects/PartialReID/configs/partial_market.yml'`

**Comment by LoryMANG** [comment]
> 11G 应该才行，你可以试试把 input size 改成 128x256，另外去掉 non-local， `WITH_NL=False`

Size那边是在配置文件里修改下面这里吗？
Input:
    SIZE_TRAIN:[256,128]
    SIZE_TEST:[256,128]

**Comment by L1aoXingyu** [comment]
是的

**Comment by LoryMANG** [comment]
> 是的

但我改了之后有个报错：
Traceback (most recent call last):
  File "projects/PartialReID/train_net.py", line 79, in <module>
    main(args)
  File "projects/PartialReID/train_net.py", line 73, in main
    return trainer.train()
  File "./fastreid/engine/defaults.py", line 353, in train
    super().train(self.start_iter, self.max_iter)
  File "./fastreid/engine/train_loop.py", line 126, in train
    self.after_train()
  File "./fastreid/engine/train_loop.py", line 134, in after_train
    h.after_train()
  File "./fastreid/engine/hooks.py", line 347, in after_train
    self._do_eval()
  File "./fastreid/engine/hooks.py", line 314, in _do_eval
    results = self._func()
  File "./fastreid/engine/defaults.py", line 311, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "./fastreid/engine/defaults.py", line 452, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "./fastreid/evaluation/evaluator.py", line 115, in inference_on_dataset
    outputs = model(inputs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "./fastreid/modeling/meta_arch/baseline.py", line 48, in forward
    pred_feat = self.inference(batched_inputs)
  File "./fastreid/modeling/meta_arch/baseline.py", line 65, in inference
    pred_feat = self.heads(features)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "./projects/PartialReID/partialreid/dsr_head.py", line 103, in forward
    foreground_feat, mask_weight, mask_weight_norm = self.occ_unit(features)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "./projects/PartialReID/partialreid/dsr_head.py", line 47, in forward
    global_feats = mask_score.matmul(SpaFeat1).view(SpaFeat1.shape[0], -1, 1, 1)
RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:558

**Comment by L1aoXingyu** [comment]
你在跑 `partialReID` 的结果吗

**Comment by finger-monkey** [comment]
> CUDA_VISIBLE_DEVICES='0,1,2,3' python3 projects/PartialReID/train_net.py --config-file 'projects/PartialReID/configs/partial_market.yml'

好的，问题已解决

**Comment by LoryMANG** [comment]
> 你在跑 `partialReID` 的结果吗

是的

**Comment by sky186** [comment]
@L1aoXingyu 
您好，训练中途报的这个cuda of memory
python3.6 ./tools/train_net.py --config-file ./configs/DukeMTMC/mgn_R50-ibn.yml 
训练报错，正常训练测试几轮之后，出现训练错误超出cuda，难道是cuda 问题吗，我的卡只用了一半的容量，单卡训练的，训练128batch   test 64 batch，我看不明白到底什么引起的这个问题，前面训的好好的后面就报cuda 不够了
参数的话，batch 改动，加了WITH_IBN: True，其他都没变

Exception during training
...
RuntimeError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 7.93 GiB total capacity; 7.02 GiB already allocated; 187.25 MiB free; 7.21 GiB reserved in total by PyTorch)

其中的参数
MODEL:
  BACKBONE:
    WITH_IBN: True  #这个参数你没有写我加进去的，不加加载 ibn ,那边的代码处理的不对，
    PRETRAIN_PATH: "/home/reid_pretrained/resnet50_ibn_a.pth.tar"

#￥################################################
训练的打印信息

[06/22 13:37:21 fastreid.utils.events]: eta: 3:33:24  iter: 999  total_loss: 55.581  b1_loss_cls: 6.445  b1_loss_triplet: 0.752  b2_loss_cls: 6.467  b2_loss_triplet: 0.740  b3_loss_cls: 6.480  b3_loss_triplet: 0.765  b21_loss_cls: 6.430  b21_loss_triplet: 0.814  b31_loss_cls: 6.382  b31_loss_triplet: 0.877  b22_loss_cls: 6.444  b32_loss_cls: 6.430  b33_loss_cls: 6.480  time: 0.7509  data_time: 0.0045  lr: 1.77e-04  max_mem: 6449M
[06/22 13:39:44 fastreid.utils.events]: eta: 3:30:53  iter: 1199  total_loss: 53.186  b1_loss_cls: 6.121  b1_loss_triplet: 0.752  b2_loss_cls: 6.106  b2_loss_triplet: 0.745  b3_loss_cls: 6.096  b3_loss_triplet: 0.750  b21_loss_cls: 6.187  b21_loss_triplet: 0.821  b31_loss_cls: 6.170  b31_loss_triplet: 0.906  b22_loss_cls: 6.137  b32_loss_cls: 6.190  b33_loss_cls: 6.140  time: 0.7451  data_time: 0.0050  lr: 2.11e-04  max_mem: 6449M
[06/22 13:42:10 fastreid.utils.events]: eta: 3:28:15  iter: 1399  total_loss: 52.973  b1_loss_cls: 6.130  b1_loss_triplet: 0.677  b2_loss_cls: 6.182  b2_loss_triplet: 0.673  b3_loss_cls: 6.123  b3_loss_triplet: 0.667  b21_loss_cls: 6.137  b21_loss_triplet: 0.753  b31_loss_cls: 6.218  b31_loss_triplet: 0.848  b22_loss_cls: 6.162  b32_loss_cls: 6.157  b33_loss_cls: 6.169  time: 0.7432  data_time: 0.0039  lr: 2.46e-04  max_mem: 6449M
[06/22 13:44:36 fastreid.utils.events]: eta: 3:19:26  iter: 1599  total_loss: 47.348  b1_loss_cls: 5.475  b1_loss_triplet: 0.656  b2_loss_cls: 5.457  b2_loss_triplet: 0.650  b3_loss_cls: 5.431  b3_loss_triplet: 0.635  b21_loss_cls: 5.497  b21_loss_triplet: 0.694  b31_loss_cls: 5.555  b31_loss_triplet: 0.789  b22_loss_cls: 5.540  b32_loss_cls: 5.630  b33_loss_cls: 5.577  time: 0.7416  data_time: 0.0013  lr: 2.81e-04  max_mem: 6449M
[06/22 13:47:03 fastreid.utils.events]: eta: 3:16:49  iter: 1799  total_loss: 47.123  b1_loss_cls: 5.372  b1_loss_triplet: 0.603  b2_loss_cls: 5.319  b2_loss_triplet: 0.609  b3_loss_cls: 5.406  b3_loss_triplet: 0.603  b21_loss_cls: 5.440  b21_loss_triplet: 0.666  b31_loss_cls: 5.488  b31_loss_triplet: 0.719  b22_loss_cls: 5.492  b32_loss_cls: 5.589  b33_loss_cls: 5.539  time: 0.7403  data_time: 0.0041  lr: 3.15e-04  max_mem: 6449M
[06/22 13:49:29 fastreid.engine.defaults]: prepare test set
[06/22 13:49:29 fastreid.data.datasets.bases]: => Loaded DukeMTMC
[06/22 13:49:29 fastreid.data.datasets.bases]:   ----------------------------------------
[06/22 13:49:29 fastreid.data.datasets.bases]:   subset   | # ids | # images | # cameras
[06/22 13:49:29 fastreid.data.datasets.bases]:   ----------------------------------------
[06/22 13:49:29 fastreid.data.datasets.bases]:   query    |   702 |     2228 |         8
[06/22 13:49:29 fastreid.data.datasets.bases]:   gallery  |  1110 |    17661 |         8
[06/22 13:49:29 fastreid.data.datasets.bases]:   ----------------------------------------
[06/22 13:49:29 fastreid.evaluation.evaluator]: Start inference on 19889 images
[06/22 13:49:33 fastreid.evaluation.evaluator]: Inference done 11/311. 0.2859 s / img. ETA=0:01:26
[06/22 13:50:04 fastreid.evaluation.evaluator]: Inference done 98/311. 0.3387 s / img. ETA=0:01:13
[06/22 13:50:34 fastreid.evaluation.evaluator]: Inference done 185/311. 0.3405 s / img. ETA=0:00:43
[06/22 13:51:04 fastreid.evaluation.evaluator]: Inference done 272/311. 0.3411 s / img. ETA=0:00:13
[06/22 13:51:18 fastreid.evaluation.evaluator]: Total inference time: 0:01:46.591542 (0.348338 s / img per device)
[06/22 13:51:18 fastreid.evaluation.evaluator]: Total inference pure compute time: 0:01:44 (0.342099 s / img per device)
[06/22 13:52:39 fastreid.engine.defaults]: Evaluation results for DukeMTMC in csv format:
[06/22 13:52:39 fastreid.evaluation.testing]: Task: Rank-1
[06/22 13:52:39 fastreid.evaluation.testing]: 14.8%
[06/22 13:52:39 fastreid.evaluation.testing]: Task: Rank-5
[06/22 13:52:39 fastreid.evaluation.testing]: 26.0%
[06/22 13:52:39 fastreid.evaluation.testing]: Task: Rank-10
[06/22 13:52:39 fastreid.evaluation.testing]: 31.1%
[06/22 13:52:39 fastreid.evaluation.testing]: Task: mAP
[06/22 13:52:39 fastreid.evaluation.testing]: 5.7%
[06/22 13:52:39 fastreid.evaluation.testing]: Task: mINP
[06/22 13:52:39 fastreid.evaluation.testing]: 0.3%
[06/22 13:52:39 fastreid.evaluation.testing]: Task: TPR@FPR=0.0001
[06/22 13:52:39 fastreid.evaluation.testing]: 0.0%
[06/22 13:52:39 fastreid.evaluation.testing]: Task: TPR@FPR=0.001
[06/22 13:52:39 fastreid.evaluation.testing]: 0.8%
[06/22 13:52:39 fastreid.evaluation.testing]: Task: TPR@FPR=0.01
[06/22 13:52:39 fastreid.evaluation.testing]: 5.4%
[06/22 13:52:39 fastreid.utils.events]: eta: 3:14:17  iter: 1999  total_loss: 47.093  b1_loss_cls: 5.489  b1_loss_triplet: 0.585  b2_loss_cls: 5.435  b2_loss_triplet: 0.587  b3_loss_cls: 5.516  b3_loss_triplet: 0.597  b21_loss_cls: 5.510  b21_loss_triplet: 0.660  b31_loss_cls: 5.644  b31_loss_triplet: 0.722  b22_loss_cls: 5.560  b32_loss_cls: 5.554  b33_loss_cls: 5.547  time: 0.7394  data_time: 0.0048  lr: 3.50e-04  max_mem: 6449M
ERROR [06/22 13:52:39 fastreid.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "./fastreid/engine/train_loop.py", line 121, in train
    self.run_step()
  File "./fastreid/engine/train_loop.py", line 202, in run_step
    outputs = self.model(data)  #一次加载 batch 大小的数据 多卡/卡的数量，这里就是batch size,也是总的batch
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "./fastreid/modeling/meta_arch/mgn.py", line 128, in forward
    features = self.backbone(images)  # (bs, 2048, 16, 8)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "./fastreid/modeling/backbones/resnet.py", line 107, in forward
    out = self.conv3(out)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/home/shiyy/.local/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 7.93 GiB total capacity; 7.02 GiB already allocated; 187.25 MiB free; 7.21 GiB reserved in total by PyTorch)
[06/22 13:52:40 fastreid.engine.hooks]: Overall training speed: 1998 iterations in 0:24:37 (0.7395 s / it)
[06/22 13:52:40 fastreid.engine.hooks]: Total training time: 0:31:07 (0:06:30 on hooks)
[06/22 13:52:40 fastreid.engine.defaults]: prepare test set
[06/22 13:52:40 fastreid.data.datasets.bases]: => Loaded DukeMTMC
[06/22 13:52:40 fastreid.data.datasets.bases]:   ----------------------------------------
[06/22 13:52:40 fastreid.data.datasets.bases]:   subset   | # ids | # images | # cameras
[06/22 13:52:40 fastreid.data.datasets.bases]:   ----------------------------------------
[06/22 13:52:40 fastreid.data.datasets.bases]:   query    |   702 |     2228 |         8
[06/22 13:52:40 fastreid.data.datasets.bases]:   gallery  |  1110 |    17661 |         8
[06/22 13:52:40 fastreid.data.datasets.bases]:   ----------------------------------------
[06/22 13:52:40 fastreid.evaluation.evaluator]: Start inference on 19889 images
[06/22 13:52:44 fastreid.evaluation.evaluator]: Inference done 11/311. 0.2732 s / img. ETA=0:01:23
[06/22 13:53:14 fastreid.evaluation.evaluator]: Inference done 101/311. 0.3260 s / img. ETA=0:01:09
[06/22 13:53:44 fastreid.evaluation.evaluator]: Inference done 191/311. 0.3285 s / img. ETA=0:00:39
[06/22 13:54:14 fastreid.evaluation.evaluator]: Inference done 279/311. 0.3306 s / img. ETA=0:00:10
[06/22 13:54:26 fastreid.evaluation.evaluator]: Total inference time: 0:01:43.439144 (0.338036 s / img per device)
[06/22 13:54:26 fastreid.evaluation.evaluator]: Total inference pure compute time: 0:01:41 (0.332554 s / img per device)
[06/22 13:55:47 fastreid.engine.defaults]: Evaluation results for DukeMTMC in csv format:
[06/22 13:55:47 fastreid.evaluation.testing]: Task: Rank-1
[06/22 13:55:47 fastreid.evaluation.testing]: 14.4%
[06/22 13:55:47 fastreid.evaluation.testing]: Task: Rank-5
[06/22 13:55:47 fastreid.evaluation.testing]: 25.3%
[06/22 13:55:47 fastreid.evaluation.testing]: Task: Rank-10
[06/22 13:55:47 fastreid.evaluation.testing]: 30.5%
[06/22 13:55:47 fastreid.evaluation.testing]: Task: mAP
[06/22 13:55:47 fastreid.evaluation.testing]: 5.4%
[06/22 13:55:47 fastreid.evaluation.testing]: Task: mINP
[06/22 13:55:47 fastreid.evaluation.testing]: 0.3%
[06/22 13:55:47 fastreid.evaluation.testing]: Task: TPR@FPR=0.0001
[06/22 13:55:47 fastreid.evaluation.testing]: 0.0%
[06/22 13:55:47 fastreid.evaluation.testing]: Task: TPR@FPR=0.001
[06/22 13:55:47 fastreid.evaluation.testing]: 0.7%
[06/22 13:55:47 fastreid.evaluation.testing]: Task: TPR@FPR=0.01
[06/22 13:55:47 fastreid.evaluation.testing]: 5.1%
shiyy@200:~/nas/all_workspace/ReID/fast-reid$ ^C
shiyy@200:~/nas/all_workspace/ReID/fast-reid$

**Comment by gmt710** [comment]
> > > > 无法指定用某个GPU训练吗？
> > > 
> > > 
> > > 可以用CUDA_VISIBLE_DEVICES＝0 来指定gpu
> > 
> > 
> > 配置系统里似乎并没有这个参数可以用哦
> 
> 参考这样的写法
> `CUDA_VISIBLE_DEVICES='0,1,2,3' python3 projects/PartialReID/train_net.py --config-file 'projects/PartialReID/configs/partial_market.yml'`

现在训练需要带上这个参数“--num-gpus gpu个数”，才能真正的用到多GPU训练。
