### ISSUE TITLE
用自己的reid数据集训练没有问题，eval出现了问题

### ISSUE THREAD

**Issue by qianjinhao** [JDAI-CV/fast-reid#94]
检查了train,query,gallery都是由数据的，log也显示出已经载入了。但是eval出现了下面的错误。

Traceback (most recent call last):
  File "tools/train_net.py", line 77, in <module>
    main(args)
  File "tools/train_net.py", line 71, in main
    return trainer.train()
  File "./fastreid/engine/defaults.py", line 353, in train
    super().train(self.start_iter, self.max_iter)
  File "./fastreid/engine/train_loop.py", line 126, in train
    self.after_train()
  File "./fastreid/engine/train_loop.py", line 134, in after_train
    h.after_train()
  File "./fastreid/engine/hooks.py", line 347, in after_train
    self._do_eval()
  File "./fastreid/engine/hooks.py", line 314, in _do_eval
    results = self._func()
  File "./fastreid/engine/defaults.py", line 311, in test_and_save_results
    self._last_eval_results = self.test(self.cfg, self.model)
  File "./fastreid/engine/defaults.py", line 453, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "./fastreid/evaluation/evaluator.py", line 119, in inference_on_dataset
    evaluator.process(outputs)
  File "./fastreid/evaluation/reid_evaluation.py", line 40, in process
    self.pids.extend(outputs[1].cpu().numpy())
AttributeError: 'NoneType' object has no attribute 'cpu'

**Comment by L1aoXingyu** [comment]
应该是你的数据读入写的有问题，这里的错误是 `outputs[1]` 是空的，一般我们的 `outputs` 是由 feature，pid 和 camid 构成，你可以打断点调试一下。

**Comment by qianjinhao** [comment]
> 应该是你的数据读入写的有问题，这里的错误是 `outputs[1]` 是空的，一般我们的 `outputs` 是由 feature，pid 和 camid 构成，你可以打断点调试一下。
test_set = CommDataset(test_items, test_transforms, relabel=True) 
代码默认为False，我改成True运行，测试时候没问题，不知道什么原因？

**Comment by L1aoXingyu** [comment]
可能是你测试集的 label 并不是数字，这样就会有问题

**Comment by qianjinhao** [comment]
> 可能是你测试集的 label 并不是数字，这样就会有问题

有可能，因为我没有按照你的库的方式组织数据集，在common.py中重新组织多个数据集那部分会有问题，前缀那部分在我这里就是绝对地址的prefix而不是数据集的prefix。

**Comment by L1aoXingyu** [comment]
多数据集训练那里使用 prefix 确实不太合理，我最近正在想办法修改，如果你有好的建议，也可以提。不妥测试集是不会用 prefix 的，测试集所有的 id 都是数字。

**Comment by L1aoXingyu** [comment]
目前对数据集重新做了配置，在每个数据集初始化的时候比较加上 prefix

https://github.com/JDAI-CV/fast-reid/blob/64861ea6c85122bbf8577c10bd7fc6e551495b3a/fastreid/data/datasets/dukemtmcreid.py#L66
